apiVersion: v1
kind: Secret
metadata:
  name: paperless-secret
stringData:
  PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:tf9CRlzWvuEGDqZPuSTOso4fqFE41FuNU6YteKahbPGQ5DYOVcRgsJTXtr8HdtEE8V304TobEFPpyEON2oCJyA==,iv:sIKD0ag4p7g6r8x5/iLbKhX8JquG75gRN+rVTAsHXTo=,tag:YzhYJpG3qyKhrbexTa/dxg==,type:str]
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:yDWqE94=,iv:EnWbz3NVNs/Li95OEncFCmm8EJPsoB1+ayX6r5ifmdw=,tag:RDC8oWOxwmboaLF0BDkdMQ==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:V94ZoKkBuwNwSJZMzEz9xhLmwkGwwPgD,iv:AU7T1pv+DxtPU24d0QCOxJKqg7Y7X9YlySpV1QxSl1s=,tag:Fk/9grZLE5qhay7p3aEHkA==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:cSpIeeLtugj2v1ENKgZrTGBXP+it1QJTDMX0VtG7FVUN/VNcplrgsUX7+bCMnct06LAAAGchLcj94zh8NIGs5Rp3RFZ9tZas/0b3tR9To7tkR2E0X4+8xVBhVnWh5GrdtmMYOrmGyDzONWHROJ40Y6u5fkunIgcJzvw33W7DhHwKIArHXKUfpfNg4EHoR0zDG+JlaLlvcdapfkQmHGCqPrR+jfjRr6/m+R+2gA1iw/3l0a13EoR5EALk1wpdkoRLjy+OWC5p8mjayXN+6ru0QCP5psvjdPmcd5W/tN7PrkbfuLNu2CxxmprJ8nun5HJityEVxtHHEw+EQ3MC3RiU555y6uf35df/K8A/1Rvlu7j2eSJWjw1K0WqyeB9u841QGfs=,iv:RpAoxO2SjLeGv82zFGYC3V6QZMyNK+/Q71GQ4YsFI14=,tag:5rvwasXtOCilIRYTkphNVg==,type:str]
  PAPERLESS_GMAIL_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:BWwDt18LgmUBnxpOqEfhALbjEEo/83ahejJjGv74DgxJZXRXIPixl91BEDjVYsIqgkj6K300AALq0t+mY6yCzF/vXS1/Kwqf,iv:+72pqQmtsyQbW4FSbLDkEn5LFJiPQgu+L0Si5KKgyTk=,tag:rgOeEftAe3Z3FDIs8A7ZUA==,type:str]
  PAPERLESS_GMAIL_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:eEQZKCsMJpbmsbkODp/JZ6i4VFNlehwG7u4zRLK8xCLb6tA=,iv:tUIi9wdznq9CDqSyP5ERoURkivwtvVZDPkriBaos9yw=,tag:4VaIpiMl7Uay8akqmLvqrA==,type:str]
sops:
  lastmodified: "2026-04-30T10:09:58Z"
  mac: ENC[AES256_GCM,data:SQuHAOwRQTAVJjBxNbsY7VI9g2bcJvjJY3LqxF3mLd1ATd1ou6HreLk4W+J4wOTsUGUBYJY0ZXXDgHdwcEXVXx9Dbsial1m0Cc6No9+ADRraZ+8E7rVdTyQkqz7yCBewIhmKTRkncxF7uWNn93pNoixRRD8t9fMUzV8rGEQ+UMc=,iv:lg990zld6O0qsglfdwgUqNyD8QJKqdxHBzj0iAPjE6Q=,tag:wW0ZLr9ABc5HTb0RLZHBjw==,type:str]
  pgp:
    - created_at: "2026-04-30T10:09:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//UVgHyTmt+c7LRUly/vgaOMx/F7LEHumn6VQDl8DF+ApZ
        azray19Dp+LT0YucgWwMBj9YDkmrkjMB902fT4Np3UNZ1hLhBPFe3NsgZ8QeO57P
        wJOUgI8VEejKUi0LYmHiDXkj/tgAjLZo3BXL+2GVXOMM2F6adN+F+uFrAjN7qlri
        8GCurg2Z477c3bbuECfnhnJ1mwvJ+KdHHQf+oHTTzZHHX/986IvPPFbpLU4VZtH5
        4l8Wi33jhL/1phH3ZxbYRvh/2U1RUVHKPK/CKPQyk/EL4R9znI79qZFkFxXhyhUH
        23IUav7xGUcRvlDRu6ldk/6nd4CA7e2ngNrVANOTdgo4stUjAfO9GxqXiEeRV5cv
        6XqM9in9AZO4bSwgl5boUOLpUmAJewlyb1D77z6W4cFArCjI76s/i9V08/IGy7Z6
        v5E9LjwMlMxLrc+DBY+whsxl5rV8Liq+u1sv5rpR7aYrw4CUdKgL2ry8R5Etr1IZ
        jGeTE9ASAQwFB3b9gkOp5NfLrXbqe8TPl4x51OabL5DZJO6DQ/8SWQs3S2ZAwq3c
        1Gbx8kIMeWzy0qTQxUeHEXkm36Qh6f89NJhLAoBqxSAtbzYCcekqLI2ZigFvXuGs
        LVwHk8SqFxBkAU//9IcfdlZ09wiHfT5FYVQ/2YChDBNw94wrAu2Qhjp2rfdiqmjS
        XgEPvJqApUx4nmk3nIKPwnBU4V3ralW692jjbOVuPtp+ZZzPvjtOQ6nhPd9uwQBq
        9pLO35Ou3VTkopcCIqFLdGIrlmrd6TaSrKvZDArsHXmVuTnOdS2iQSSrHtEi7sg=
        =jzZJ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
