---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paperless-backup-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paperless-backup-job
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &name paperless-backup-job
subjects:
  - kind: ServiceAccount
    name: *name
    namespace: default
roleRef:
  kind: Role
  name: *name
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-backup-job
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(TZ="Europe/Berlin" date +"%Y-%m-%d_%H-%M-%S")
    FILENAME="export-${TIMESTAMP}"
    FILENAME_ZIP="${FILENAME}.zip"
    PL_POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=paperless -n default -o jsonpath='{.items[0].metadata.name}')

    echo "Creating paperless-ngx backup"
    kubectl exec -n default ${PL_POD_NAME} --container app -- \
      document_exporter \
      --no-progress-bar \
      --split-manifest \
      --use-folder-prefix \
      --zip \
      --zip-name ${FILENAME} \
      /data/nfs/export

    echo "finished paperless-ngx backup"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: paperless-backup
  namespace: default
spec:
  schedule: "0 4 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 60
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccount: paperless-backup-job
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command: ["sh", "-c", "/scripts/backup.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts/backup.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: paperless-backup-job
                items:
                  - key: backup.sh
                    path: backup.sh
                defaultMode: 0555 # read and execute
