apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-backup-nfs
spec:
  storageClassName: paperless-backup-nfs
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/backup/apps/paperless
    server: 192.168.0.104
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-backup-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: paperless-backup-nfs
  resources:
    requests:
      storage: 20Gi
