apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-backup-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/backup/apps/paperless
    server: 192.168.1.104
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-backup-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: paperless-backup-nfs
