apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: &name paperless-data
  namespace: default
  labels:
    backup: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-ceph-block
