apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  releaseName: cnpg
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 50m
  install:
    remediation:
      retries: 3
