---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-mongodb
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://registry-1.docker.io/bitnamicharts/mongodb
  ref:
    tag: 16.5.44
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.1.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: any-sync-mongodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitnami-mongodb
  values:
    #TODO auth
    architecture: replicaset
    replicaCount: 1
    auth:
      enabled: false
    arbiter:
      enabled: false
      pdb:
        minAvailable: 0
    pdb:
      minAvailable: 0
    persistence:
      existingClaim: anytype-sync-mongodb
    resources:
      requests:
        memory: 1Gi
        cpu: 400m
