apiVersion: v1
kind: Secret
metadata:
  name: stash-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:LmjhLxTX96h2CFN/uNIY2LqQ3Bk5peOGcXb1+UlSJU+wJQR9kKBsumCI/sH9koTRmtZsLKrSBaBM+L4O7Gs4IygIcbwhjq+2OlMfka7QePpxb3E03m9L18LzItXdJT6Q1wAEreiMXJf6Tb5953pZ5myE8mJjJylffOylONl3tb9po4JjMDU4W3KKJeaLTQfNrv8zsB1PtLKuUZgw0BZb4K8=,iv:kLf2GkWOuFy0+9Aheazn1QNb+Ot6kkHXb4oS1GqvADo=,tag:zZZg/tsbXNiCgIemdYTXQg==,type:str]
sops:
  lastmodified: "2026-03-29T11:18:10Z"
  mac: ENC[AES256_GCM,data:AHoLK3ZVpP02tZRKMtWYvm9fBbgWvRuZlNMcxFyJQ2qQWtaAIhsW+hCZvZfGqgMzlwmUD8wYeU45E/WgFP7pGvJfHtsi0zMbQbHe67QQh5POMMywARMjuBwxxSChRj1ZgOEnYvhfwhNM1QovWKOJjWuco6Do8hE9s1b3hr+nCxY=,iv:sEMS6qO5Y3qKhv9cNdobX0vHCK7pZrm9QQiXCdLB2DI=,tag:GPLJwB+uljKjJeXpzqvtYA==,type:str]
  pgp:
    - created_at: "2026-03-29T11:18:10Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/+JtkSAoKGKxMpEmZ49SNqC9WU35DFYmO7CPQKh8Ckt8g4
        5/lmM1Zb4xgxS4LchX0wLiPTqlJloFmyAfw2ZkvrZfXrH8YinccoYAiHuZK2Xx6B
        b16ouF02ZoXW8KCfhnRclVcmmuVsFQfOG4bGpYCHTVUsHqLFEySWIOkkdN5+Gbs1
        pR/RsTzD2WZ9Tmo3FarjXEmnUyoC3c/lKMZzK5pNhkBCRACiWpWWdQpD3zUOXvIN
        Pt3fDZr851ocS3HnoZ3rAa1sgH9iY+dOlMWCbzXfuZDdYHEzMcnQ6Bnq46rVCMWP
        vgjI6Ni0N9HCFU2U47bvkcos1fVOXfci930UVWZJ15F/A4dkM4MUiOgPSUOcEsWM
        CmZTlKl74pdsd51Rf16FuYqtJPDI0t5A1MydTnv1gAIS3SvZVVyBs44Jo2yMSDkZ
        MuXV57MjXs3cRlC/edZkNIo4E2drpmtM6AxTe017cBLf9T1TVIQ3H8mKU5z4oYvc
        IGZqG4WqIxcK+2+VDkmz6Wy3s8llAGZvjIOBtd1gQe6g736Y9IKjNi3ntS62Han5
        NjJxX+l7RRJZb+GvDZJnBVr7zoab8+t16EiyTePE4ipetKhbdV9Cv8fThO3F8h2W
        MGydAHeJzuoHLoKIKLYe+2mU7d7W4PhHso9c5SZJaRk/FB+rd/GhoLjRDJgC6+/S
        XgGyWhkrMiPWbS4PxrSZBxVshf2S83FEM6B5zGpNPATVZNrUjEplVMoyoHeEIhO1
        sSd0xb9bpuN36UJFn2s9XYgxkKjtAk6ljoZeqmhHn9E6Hu5fZc8PovFx3i3UqHs=
        =sWcw
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
