---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  chartRef:
    kind: OCIRepository
    name: nvidia-device-plugin
  interval: 1h
  values:
    runtimeClassName: nvidia
    tolerations:
      - key: "ai"
        operator: "Equal"
        value: "workload"
        effect: "NoSchedule"
    nodeSelector:
      nvidia.com/gpu.present: "true"
    securityContext:
      privileged: true
    config:
      map:
        default: |-
          version: v1
          flags:
            migStrategy: none
          sharing:
            timeSlicing:
              renameByDefault: false
              failRequestsGreaterThanOne: false
              resources:
                - name: nvidia.com/gpu
                  replicas: 4
