apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
stringData:
  LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:H/USA1QMkeJv77b2f91FYXB6f5YhAO7l7DGAzgoQs+I=,iv:SiCh8DmBKxvKz0qx8QAgFh5Wuf2m79Y17GBNtXhqtLo=,tag:JiY8b2q8Cs7wvRWmTAAegA==,type:str]
sops:
  lastmodified: "2026-03-03T11:52:32Z"
  mac: ENC[AES256_GCM,data:Tt2UjDiqiKyip5EVECDFfA43iAzZ52Y6KrX4g/+JkFQvwxkUOe+I/uvN/eOpMhX9IMTBLgahBu0Ij5ELsmGpWOd/059B2gNn/mCTe1eMp9zC5d+PJGNMkTPhKICpFFge8Th0LrQ238bjdigmVcaB46V06xUOJW3jjbgE4UG/hWY=,iv:1WhI6pBPywBlQyRYs+bDSN7Sl9feoNxLCLyZiqkvnhU=,tag:hXKBi3vsCb961FKATDrDRg==,type:str]
  pgp:
    - created_at: "2026-03-03T11:52:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/+Mf9l1dkNBp/17+O8hTsLgfniiB3td5nQ3p2I1xjGV/r6
        wFml/nQDeSLZnjM2HiMNcHrxrvKQBa7nL9vHhJJoC3QYf0cv9aoZziwJI4BiiNrm
        S0DjeHK5dtO5WddwBcqtAJTxJ/SdooQAKmkgb6frD87g1sX51G/9EF40SoRjxLjm
        a3bN3aWJba3a1Yyla7zU+HyOuuDNPm4ZKcSNG5+lkDzYSgpQ7UXEUIeNAWgjxTEN
        kg68Fvwx4S2ZL3XXHRQYG88CM0PQgn507Z86rKLW3fcPHLwRVEIM5f3+oxWBrMH5
        gd0ny2+pHmLCi3yS3NsfbUKch3JKLvKDxXD8e2dQzhpBCkjHx0u3JCo9kGlngpme
        v+dfyuVjuV+UhSuM3Rw9rhDdr1dYMHBzE6wXtYW5eR0LcQDZXCdYhM5SuqXgkrvz
        HUTo3aIt7rgLYdjtF5YB+X/FydZmrQrq7PDHARy4xzTB+bk6v/YH4Mz4YDD/CNkM
        7GzmS4OtI+AmhmhPt5MADIW22V4DhoiOlHdExEcvTBupOUS/g4oeslyDnmWoatBS
        aTbRKBLwdjoAVWj3kO/AT+0byXuKIahEz6Wy1dhSPvzhqydxX4Lodbc0APuiuHsy
        8+pJvbIHmPhEPvjeE82EjN95G0hzpY1sjn5UBnebbNLq/7j/od6vdwDvcHdJCFPS
        XAGUT75+kJR+6/iqbvAgXbzeGLG8rzh6EeXMzv89oIJPQI91tDwLintgMCW2Q9+P
        p4J0IscrvkRSkS7gPbHNlC5seVZbMtqthXzrfEO+N3y64DvAA1WW0c1LofTw
        =kb8N
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
