apiVersion: v1
kind: Secret
metadata:
  name: dispatcharr-gluetun-secret
stringData:
  #ENC[AES256_GCM,data:0MyUB3WffKQQC8M8uauibvdem+o=,iv:iq8jirUTUZsPZjf7pRXS3In2EahVPWgSG/qmNcNI328=,tag:zlc9UNMHuefwpGiVs7hBUw==,type:comment]
  SERVER_CITIES: ENC[AES256_GCM,data:BDE2Oghm,iv:sdTj06IOy3kRvCFQEUsLKlI7+IwxOdz3Ycdq2Xb7nwE=,tag:plZp0pNLRXcisMs5zucKEg==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:1uTyfwNX,iv:TXVd7GhZEiHn1XAl05jPGj1WGiZI8bEKj/fIdrR6pRQ=,tag:rFmKhJfpKPmqyCwz1W9GSQ==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:BpkHqueGvQ==,iv:J7tU3ukUIrBRYALmnnvcfN/Vz0XOvso8BzIhPWNsllI=,tag:lZKz4a9LHrYc0JczM5+u8A==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:vRfpX1sEpnOk,iv:dP+nCEfgpKyRzUpdMp3mHuxrzVi6ryILwCtRWRLxxkU=,tag:WnhWFp635I8XntOd1PZ2hg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:TOFyLapfR8VHhS8KChy4NSTufF5eL0uU6kR8C4X8m4zsmOo2qiRdPkdHa3njJmE=,iv:7lpg+S8MYDMZOr7vgPNb1knxDvuqf+kvUUiSCOG6iM0=,tag:2dwy4sZJY4bfiw2RtJ9mCA==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:g5UasoRFf0jkI6iag2JlLJ0ojqr/hl3I6d1VcfOz4kdEYQZJX31DslMmevA=,iv:RC2C2gPv3c4amEQ1iQ4f5WCBI766tyK80Ef1470tQ3U=,tag:DG7AgsqiG9Ad2TJuMvBQAQ==,type:str]
sops:
  lastmodified: "2026-03-06T17:25:57Z"
  mac: ENC[AES256_GCM,data:gKZQCipvbGpNsZa7XQDPXWAqHiGwhsFaeVEqV8FucQV34koVYBkG/y/3N/bOEwwAOWvLFshHrJoyuWx2z37lFXT4HSHwoi2Gl8cPnJkqxXoe+sqNM3FlPNb6IrQtAJwS0UnT8FBQ3+68sINslHqjHmTqK1dtoQfIOaH27F7AjD0=,iv:X8XAvWPwPw0MvYrOrAnx8cJ7h4ntb7vE7uMr5p0T7Dk=,tag:DsJ6LmA8YHZ0yXqNIpr1pQ==,type:str]
  pgp:
    - created_at: "2026-03-06T17:25:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAlWiQJsc+kI8aorrfbpf9X/zrY16BW6XbnM7LJ+0pJ4tg
        ZaM/Q55nkRc6qJA/N8mLzzCaqCRl23GAFVi5Nrb9dXt0dtzwfN3Kh8T0jvLDA/B8
        aC9/G9Ce3mcrAInHvlX8fpyJFZzDKyn7vWEoEM6Gzol0xtwpwejd4BtA27MCs+I2
        IhihSUTG5H+9uFZ2VqIilBK1j4SaAgMH1BclT1dkCFvYUl5z+Tj4A7Oi6AQJlGqq
        hRR77axPDOknPD3I0/68WCPJhLkDriwBt0N2rO8LkbEQ/t+dv1LEVf5+TRpkyBH2
        aGWTJU5vP9/79O3gHKeDNPdBF5r4qfXIMayynOUVzREgE0TR1VLamsoBT/30QKLe
        jLOlDBkfT+4eA8n74d2Xn//fijshlG5ChNX1eDypchbuPD80n/HlxpF6FpJSzrrp
        TaXjcu8B4NaTBO15zrclQsjNcCsV5HkytHTKdIlPtwY6JM4Vvl0/s+nLZGoyPnaQ
        OSe1qt1q2ufDRwoylcLbU6L2qJZUuOOPGYxLOOpXMPxO3P2Gyzj9fRTHEyMY+zAe
        uojRMddyo/ujwgbfLW9IPtuv1TODF/CFerz8mYwRgveQMyQMyXE1UrouYn/585aM
        wJN3KjEtDE2sk1E4xKwn19InyyvDfqlm50vU1jS37XrMWg8EyTKEpn+G0ULmKZTS
        XgEBvBt6BeJtXFJrcY0wQOVpsMaBf7CnIxRXf7ZMe8uJ/HcdjLv56fEBdUoioiGX
        Zg5+BFV6ZjALd/SBdv6Qpo0xPTdmB+N+y2L6DlcIGWSoiv4O91xYuuYsG4pOxuo=
        =NW6i
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
