apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app k8up
  namespace: &ns k8up-system
spec:
  releaseName: *app
  interval: 50m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: *app
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    k8up:
      operatorNamespace: *ns
      envVars:
        - name: BACKUP_SKIP_WITHOUT_ANNOTATION
          value: "true"
