---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grist
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/grist/app
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
