# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: "v1.18.0"
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
    monitoring:
      enabled: true
    csi:
      enableLiveness: true
      serviceMonitor:
        enabled: true
      pluginTolerations:
        - key: "arm"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: v1
              kind: Service
              metadata:
                name: rook-ceph-rbd-csi-ceph-com-liveness
                namespace: rook-ceph
                labels:
                  app: csi-metrics
          - patch: |-
              apiVersion: v1
              kind: Service
              metadata:
                name: rook-ceph-cephfs-csi-ceph-com-liveness
                namespace: rook-ceph
                labels:
                  app: csi-metrics
