apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
spec:
  releaseName: rook-ceph
  chart:
    spec:
      chart: rook-ceph
      version: "v1.18.0"
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    nodeSelector:
      kubernetes.io/hostname: tc02
    csi:
      pluginTolerations:
        - key: "arm"
          operator: "Exists"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
