---
# renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
#
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
  - pre-push
  - commit-msg

default_stages:
  - pre-commit

exclude: |
  (?x)^(
    ^.*(copier-answers\.ya?ml)$ |
    ^.*\.rej$ |
    ^ansible/.*$ |
    ^logseq/.*$ |
    ^.*gotk-components\.yaml$
  )$

repos:
  - repo: local
    hooks:
      - id: forbid-yml
        name: Forbid .yml file extensions (use .yaml)
        entry: YAML file extensions must be .yaml
        language: fail
        files: \.yml$
        exclude: |
          (?x)^(
            ^.*(copier-answers\.ya?ml)$ |
            ^ansible/.*$
          )$
  # renovate: datasource=github-tags depName=pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v6.0.0"
    hooks:
      - id: check-added-large-files
        args: [--maxkb=500000]
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: detect-private-key
        stages: [pre-commit]
      - id: check-case-conflict
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=Lucas-C/pre-commit-hooks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: "v1.5.5"
    hooks:
      - id: remove-crlf
        stages: [pre-commit]
      # - id: remove-tabs
      #   stages: [pre-commit]
  # renovate: datasource=github-tags depName=sirosen/texthooks
  - repo: https://github.com/sirosen/texthooks
    rev: "0.7.1"
    hooks:
      - id: fix-smartquotes
        stages: [pre-commit]
      - id: fix-ligatures
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=zricethezav/gitleaks
  - repo: https://github.com/zricethezav/gitleaks
    rev: "v8.28.0"
    hooks:
      - id: gitleaks
  # renovate: datasource=github-tags depName=stefmolin/exif-stripper
  - repo: https://github.com/stefmolin/exif-stripper
    rev: 1.1.0
    hooks:
      - id: strip-exif
        name: Strip exif metadata from images
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=igorshubovych/markdownlint-cli
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: "v0.45.0"
  #   hooks:
  #     - id: markdownlint
  #       name: Lint markdown files
  #       args:
  #         - --config=.markdownlint.yaml
  #         - --fix
  #       stages: [pre-commit]
  # - repo: local
  #   hooks:
  #     - id: shellcheck
  #       name: Lint shell scripts
  #       language: system
  #       entry: shellcheck
  #       types: ["shell"]
  #       exclude: "^.*zsh$" # ignore '*.zsh" scripts'
  #       stages: [pre-commit]
  # renovate: datasource=github-tags depName=scop/pre-commit-shfmt versioning=loose
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: "v3.8.0-1"
    hooks:
      - id: shfmt
        name: Format shell scripts
        args:
          - "--binary-next-line"
          - "--case-indent"
          - "--space-redirects"
          - "--indent"
          - "2"
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: prettier
        name: Format with Prettier
        language: system
        entry: prettier
        args:
          - --write
          - --ignore-unknown
          - --no-error-on-unmatched-pattern
          # - "--ignore-path '**/*.md'"
          # - "--ignore-path '**/*.y*ml'"
        stages: [pre-commit]
  # renovate: datasource=github-tags depName=adrienverge/yamllint
  - repo: https://github.com/adrienverge/yamllint
    rev: "v1.37.1"
    hooks:
      - id: yamllint
        name: Lint yaml files
        args: [-c=.yamllint.yaml]
        stages: [pre-commit]
  ### NOTE: ".typos.toml" may be required to have _already been committed_
  ### in order for typos pre-commit hook to read it.
  ### In this case, comment out this block until ".typos.toml" has been committed successfully
  # renovate: datasource=github-tags depName=crate-ci/typos
  # - repo: https://github.com/crate-ci/typos
  #   rev: "v1.35.5"
  #   hooks:
  #     - id: typos
  #       name: Spellcheck with Typos
  #       args: ["--config", ".typos.toml"]
  #       exclude: |
  #         (?x)^(
  #           ^.*(typos\.toml)$ |
  #           ^.*(\.typos\.toml)$ |
  #           ^.*(\.sops\.yaml)$ |
  #           ^.*(\.git.*)$
  #         )$
  #       stages: [pre-commit]
