role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: oc_role
    role_mapping:
      - role_name: admin
        claim_value: admin
      - role_name: user
        claim_value: user
      - role_name: guest
        claim_value: guest
