apiVersion: v1
kind: Secret
metadata:
  name: postgres-memos-superuser
stringData:
  username: ENC[AES256_GCM,data:G+Vq6tYrXmA=,iv:OdwIrqbtv6McVK2ENWdSvHwzr+9GeCJ1yr1V5os9YAo=,tag:bxLbcYjwmuAbvMmEhdKy8Q==,type:str]
  password: ENC[AES256_GCM,data:87f2DUGYFvtEX3aK9FB6ZuBlqNM80CKn,iv:H3XXGmWDYs3fvVUpoTAMnjIh/298zpq7dI64DtanXIU=,tag:itfN0h9Qk+1XvM5Sse0lRQ==,type:str]
sops:
  lastmodified: "2025-08-12T14:08:58Z"
  mac: ENC[AES256_GCM,data:aZfj1DbKj087PxzXC7Naj/r59Et6coCco9nKqS8O4raq18oFG7c8erDWjNwlfxEmOD5rUpW0CxkMuQvXDtDK1Zg0zzZFL+V9yQtM3qA8RFbegwFf2ye6OB8NKTIo8kdRPjC6d5bALKt+6H/ZCM7WBnJ/j+FfiKqV7CcZpubeaBk=,iv:DZKHB4cQC3lj2p0WutSRsV/rouwSETZBa5u9Oz0VzNk=,tag:NaSTZqhOftUlsOthM5PMYQ==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
