apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:JcCEdEtxYwFKsi3Muq20CjHX3mECkHYhsLwz4RgYaT8=,iv:t4RcQEk4ICvj58pG7U7fg0L7B2eSkX5mq4beQTH81GY=,tag:JayahGjaL4tDKJhFmD7Uxw==,type:str]
sops:
  lastmodified: "2026-02-26T11:38:04Z"
  mac: ENC[AES256_GCM,data:mBm06CW94+0p9/c4Uo9f2DV68otU3ZNIhlQh+/cIdsnsFRq+PGCbwOUI3x/vYQSCoVbuQRjkyGkuAaZ/9R1aslXYm3HmGy+XfWXK24Gt6lrKbCbVC9T1TFh7grxVmOSIVkq9ehty3QgxIloUTw6Y5+NOBw6OKQlbjBMJ5GPHz7s=,iv:AlSMFbYONXorSKpPwGe/ocDtHpgcaa1ay6sTJuyH1i0=,tag:QgbiDRsYeECTulPb4BL8aQ==,type:str]
  pgp:
    - created_at: "2026-02-26T11:38:04Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//Q1SfeKs2uvUqm3spk1ua4uVwjjr4xRcSrdNGhVV/S0K+
        VlRVZPha2oomibT5uZlEHwUtf+MBk8nvA7QTMrlcgAL6pI7hQzxlsg3k+4kGfGhl
        z/DJt2DZZn8BN8O/q9CxMkoBVRAqk4rqpOXfpmV4aHQklDxZtUzm5r4tIdB4U8EL
        BWssUGWIcNY2KkA6l/H10TNxxx0HPJBY34uvXUf284Yc3TDuz0DHZRP+slhQhJJX
        0zx98zt9J5u8uaGMgEmaLA3nx1YIw5Ju6MmTTLwAEQMqMR6teQJgSGhQkTMadYQV
        p87gbPkndvtz3pL0V9u3Cv/FAxndlT19c0hyl7CfOobJWoFw8eOvWgDcO/AlPV5G
        bHOLnl7O3HAq44irNakmK8Ffa0d8z6D3lEz5C/pje0iC55yy4+q1xPsUK8pgrWdW
        xx/IAhMF7u6btgNxRWdN7v+hhcPOfKgPOGR0O+Vc1VgqSRRZ1tTKIYFdRmgCfkMD
        lluCFi5aRMTwftkwivsTMqgl/XCjH/Vo2xyEVTE5gkFJZ7+Pqn5EN08I6cFwSbUo
        yKWsyXRI9MzBz3an8c+jezJckmxIKdKuv7h16zyMfrYczZEqOwMrKhGYaxPU4n8p
        j2Symx1+Pl0iVrxx1VPIqccIVdjkognDmvTws47ft2HMix7laj63lW0g9sOAWg7S
        XAGnqFDr21QFn9nYx8KRv9EV/Bsi70FvpX8gXFYZIeT9gJHMhL/Rpmo2mFsRC6EG
        w2hDhOo+yPDtV6NnAAgUfj1i4DZpV3eoETPhdsgR/gtwPYhCSk88CY/Evg+A
        =Pi2W
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
