apiVersion: v1
kind: Secret
metadata:
  name: teable-secret
stringData:
  BACKEND_OIDC_CLIENT_ID: ENC[AES256_GCM,data:xK60a8py,iv:aI0IP8BsFUB6Kib0s6SipqlgrXSoziVl1I/nXuh8tpA=,tag:86uoApkuhHeqc/pifz2IGw==,type:str]
  BACKEND_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:7fQjeYovZpcrhQeCV/8/Ojh2xqzb2j0cf6ylEHgVKh8=,iv:9DC3cUMgR4wiRs+cLJR7KzEM3kPRpcrLcI7Ty1hs3TQ=,tag:BaBR2eT+1HIat446KOJ+1Q==,type:str]
  SECRET_KEY: ENC[AES256_GCM,data:Vrs0kBP/t1h90IBVoaNOZRlDX1Jm1ZyHZMj6YdnO5/zh5ZlJEDGtAWUEqyuMqqv8Qfc+CUIUWJqzJVlqtisCMQ==,iv:MOGu+Cq5gv8SK7YVS1AldUE8z00YVAl3c/PiCGk0pFE=,tag:dnrXGVdTkfXHrDP9y2G3Pg==,type:str]
sops:
  lastmodified: "2025-09-13T19:20:01Z"
  mac: ENC[AES256_GCM,data:vYSBw2Rx5It2Qu6W8qGPhLIcN2+skfMRHywng3aPtD2FRKYwx5+LddXtHl4KVXc6KPxjorDzp5+fSc0W9TsRLJVXo3Vxc3iqqhbMlCejsQ8/ZPxKmn4Cg5srF/e4PhzCC8uMqVqpIKh+cAJ578o3df6mppdLOVMjVpwsWcxVjv4=,iv:9LzEEj+MOIf98pbzhZn2jvJx5G15L033lErKGhaUT4g=,tag:AznSAoVfmnwhS48rsVg0pA==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
