apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  releaseName: nextcloud
  chart:
    spec:
      chart: nextcloud
      sourceRef:
        kind: HelmRepository
        name: nextcloud
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    nextcloud:
      host: nextcloud.fdk.codes    
    ingress:
      enabled: true
      className: nginx