apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./secret.sops.yaml"
  - "./cluster.yaml"
  - "./storageclass.yaml"
  - "./objectstorage.yaml"
  - "./service-monitor.yaml"
  - "./exporter-service-monitor.yaml"
  # - "./toolbox.yaml"
