apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
stringData:
    password: ENC[AES256_GCM,data:oqCe+CLk/nxPyH4QraneoBKck01XVMLZ,iv:RBTaFYn63G16qLLNAXdUyoS3Q6vk57TttGaRN/pYqb0=,tag:eS90Sle+PMvTlz1CYCtSdw==,type:str]
sops:
    lastmodified: "2025-08-20T11:51:58Z"
    mac: ENC[AES256_GCM,data:IWz1BJWim9gh0h7ph5ch4qSDXJKPnvwncQ8Xb2a5Ej3piz2wITrBX1Dvoi49/qXpz0SeYu5wZ2Q0ceke9u4KBYqBw3TPcoOxbrAUYK8PHX6Iv+IMLHlbmXZIAcrdPCjc4AnuWYLJhaLJcjiLsMbb1xUKL4FAvrq4iaRnjVPeNww=,iv:KulBOHLXxNZ2Ps6Vx8ozSur0U9tfY+5pkCVkL2m7VtQ=,tag:+D2rh/0NK6VKU6g1LS8CIw==,type:str]
    pgp:
        - created_at: "2025-08-16T16:28:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ//STIZy+m7sFZzOXnP+TzbNbs8Svvfx6tzzHi0DLZjh671
            wO9zjlcJfbSjfyE3AWxH62Fgo7BRyNbAVWbFokPpNpEkE+pAcvci67o9JMLf5QS+
            1EASjhrezh/+IAwDBOFOY03VtJaoVi0OZBuaRb27uWAWy/t7306Xl7/R+qLDqENw
            UfyVIapJ7c/WwsZJzSysLp0/rEOkkXw0Ch2DZ5jx6VWNnJKF1TyXMI9hNbRuGR3Z
            SVhG4R0mXAUpcWYqOBz2R8gAWR9KaUqHJL0VZFnReEz8+vRB89PIgjC8F+a6c2g6
            rUCqw4kioEoWIZrynKPUN9qnlkS7+NUGMncBXphni9HFzKJKtVwCKAzR/Q7jzR9g
            RDFjexUiXtoJGZBGpF/HIHW0XCak/dVoejtbyvhY8gmalhnGstefIQMCaAp5iwdx
            RNXj8GbYvbByS16qNwiLC1R9ff1xhUb3HgzHF4Di2bVnMXywFyj3V5Mj/wtLmOZc
            6rG5CPZe2bMG1W7u815oWNULowXJYbKQwMZRRRnh5dSBzAjfM+j3dqeJlNKiaSOu
            xkuDGL3lPwYSZfiaK7VFrTORyS6KXHDwMgCjKD9YLWeWTruYx9B6T1hcRk4PxQYA
            DJ1qZQlXqBAeAeLajM6Xk5XiOJHpqbow++udCyAEBx3rC6/QWLjSo+1pqKWyKP7S
            XgGE3j26YHNZLJVaoIEMyufJPkqkCdMRR4LLrDqlALvW4WPZzkN6VssiVCoiEdWe
            e3Qp5kqmF7RJfzN4/xAaGJPMVt/+mh/5Gpy7WdMRRfVv5/z6WDmkWZBf+x8OtpY=
            =Rnf4
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-object-store-any-sync-user
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:CbXwiLJaXkCO9OPk5Sy0qwMz9BfRB/sFr6kBIQ==,iv:HnWxYXvXWbpl0cZUY4DmdI89WC7I0HFePytfC2cAXuI=,tag:KSnwtcWaSx6ttjKGsGR/ig==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ToJRz/wSA4ky45W8AfwwpEnNBv63YPlLtTvs5mwy7Lo=,iv:+AIixxxOJWt5cCO6NCLlLREaZk5Bsz0k94fxDeDx56o=,tag:A12PnrkuS56qBzbMosG9bg==,type:str]
sops:
    lastmodified: "2025-08-20T11:51:58Z"
    mac: ENC[AES256_GCM,data:IWz1BJWim9gh0h7ph5ch4qSDXJKPnvwncQ8Xb2a5Ej3piz2wITrBX1Dvoi49/qXpz0SeYu5wZ2Q0ceke9u4KBYqBw3TPcoOxbrAUYK8PHX6Iv+IMLHlbmXZIAcrdPCjc4AnuWYLJhaLJcjiLsMbb1xUKL4FAvrq4iaRnjVPeNww=,iv:KulBOHLXxNZ2Ps6Vx8ozSur0U9tfY+5pkCVkL2m7VtQ=,tag:+D2rh/0NK6VKU6g1LS8CIw==,type:str]
    pgp:
        - created_at: "2025-08-16T16:28:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ//STIZy+m7sFZzOXnP+TzbNbs8Svvfx6tzzHi0DLZjh671
            wO9zjlcJfbSjfyE3AWxH62Fgo7BRyNbAVWbFokPpNpEkE+pAcvci67o9JMLf5QS+
            1EASjhrezh/+IAwDBOFOY03VtJaoVi0OZBuaRb27uWAWy/t7306Xl7/R+qLDqENw
            UfyVIapJ7c/WwsZJzSysLp0/rEOkkXw0Ch2DZ5jx6VWNnJKF1TyXMI9hNbRuGR3Z
            SVhG4R0mXAUpcWYqOBz2R8gAWR9KaUqHJL0VZFnReEz8+vRB89PIgjC8F+a6c2g6
            rUCqw4kioEoWIZrynKPUN9qnlkS7+NUGMncBXphni9HFzKJKtVwCKAzR/Q7jzR9g
            RDFjexUiXtoJGZBGpF/HIHW0XCak/dVoejtbyvhY8gmalhnGstefIQMCaAp5iwdx
            RNXj8GbYvbByS16qNwiLC1R9ff1xhUb3HgzHF4Di2bVnMXywFyj3V5Mj/wtLmOZc
            6rG5CPZe2bMG1W7u815oWNULowXJYbKQwMZRRRnh5dSBzAjfM+j3dqeJlNKiaSOu
            xkuDGL3lPwYSZfiaK7VFrTORyS6KXHDwMgCjKD9YLWeWTruYx9B6T1hcRk4PxQYA
            DJ1qZQlXqBAeAeLajM6Xk5XiOJHpqbow++udCyAEBx3rC6/QWLjSo+1pqKWyKP7S
            XgGE3j26YHNZLJVaoIEMyufJPkqkCdMRR4LLrDqlALvW4WPZzkN6VssiVCoiEdWe
            e3Qp5kqmF7RJfzN4/xAaGJPMVt/+mh/5Gpy7WdMRRfVv5/z6WDmkWZBf+x8OtpY=
            =Rnf4
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
