apiVersion: v1
kind: Secret
metadata:
  name: immich-drop-secret
stringData:
  IMMICH_API_KEY: ENC[AES256_GCM,data:guwZ67LvtaoLBkWdjqbQ8t6aCcVP+Mat3SkkR5h/ezXrogx3Zu+HMVuE,iv:aAzuL810st2Zeu50KGVMVyo8+GMlNOpZ+yA2h6FqMHI=,tag:tT67KC4IdB6yxuyZcKPDJQ==,type:str]
sops:
  lastmodified: "2026-04-14T10:20:49Z"
  mac: ENC[AES256_GCM,data:MZ9XNbHrZdNJXNkQD/vlJj7f55UZXrah4j/QnPn9itJy2TdLhGLFbRgOgZ+Zp18BL5jHQa3DmRVxSx1pYQLSYVJcbs91XgBMesqbD8Aw38ZaUMNsYfgoB3hPcozCUJwDxquRhpb8SO3jcezaRUJ65oL33HILVzJXTIwAKeOjzl4=,iv:i9YjSS6bke40M+OKh0gYCwZTygMzpdi4qc1oiq1R37o=,tag:L6FBF6ljU7tnmCOHvNiS6w==,type:str]
  pgp:
    - created_at: "2026-04-14T10:20:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//QJKSn7sME+TbevEPLM0ZjJk9xhxOiePpWHsbPbwKOYXN
        MhPs53TKsxAU6CsER5PL7h4ZbeisyCz6H/1UJkZRVdoklemc/fjbMA3v3Y4AqRqB
        WfL7M0jCC225DzAWsTvFb6dzzWjGYK8bI+83OeQ9HnBfyTfGKPjRPH5pNi8I1EIp
        2Q6/eSG1SIa0HGhyKRMOdR4F46FdSzevTTnL09UzPamBBJtxrjPCXy1DDMmqTfqI
        iFnwXSL/hMhOGJINnBC4DRNrDzY3gfOCVfsmF9N6MwsKTfcBMmCYt5gy33+vCwKP
        TVGOx36azilmBBtglGzQAgxE5620GL4YlbpRbXXPPCvI5KlQgNb1FlSZd5XJ5VF7
        YM9e5Fvv6Iv4CHrMYssHV0IPDE/CX5ENJ5cDCBU0V02L+WeeWTa2o4fqOgsxAn7v
        8fxhdGWb/v0RfT65XeH0hHA4NTAHiLRBPRv1teZk4TNLYTDZgCONq5coJ/3J9UPu
        WqEtAu+s1UZEtP+ewYTA+f+SxADqnrCTjrIEw+VpheJKuMXUwJbfbJJGmt3m9EQU
        /f/jayRR8+UTrRHKv0z27dzLWxIureQnY4dcVBI4rDuHidqJ+QIdObUrTKwsoOQ7
        7LtyqbbqDP9AgHnGL9LFXmcKXV0qzT5frSzuYll5ZQd8cryalg6YL2vmSPfs/pLS
        XAGqpSfM0in6M4geyZi5gPtxR9Ho0nd4mXtASrclvwd4lRfhVH2TM2BPqgvlwdDx
        1EVvdyaXde/xZ9euNi8rriVBJCLUVo0RILIGTbKeQrGtMvL8r2jCeKNWcIrU
        =zzxz
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
