---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anytype-sync-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: rook-ceph-block
