# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: profilarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: profilarr
  maxHistory: 2
  install:
    timeout: 10m
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    timeout: 10m
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      profilarr:
        containers:
          app:
            image:
              repository: ghcr.io/dictionarry-hub/profilarr
              tag: 2.0.4
            env:
              TZ: ${TIMEZONE}
              PORT: &port 6868
              PUID: 1000
              PGID: 1000
              ORIGIN: https://profilarr.${SECRET_DOMAIN}
              AUTH: "off"
              UMASK: "022"
            probes:
              liveness: &probes
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 30
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 700Mi

    service:
      app:
        controller: profilarr
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "profilarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        existingClaim: profilarr
        advancedMounts:
          profilarr:
            app:
              - path: /config
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
