apiVersion: v1
kind: Secret
metadata:
  name: grafana
stringData:
  admin-user: ENC[AES256_GCM,data:fftHsjc=,iv:FqSvCMRI9n2OcJ7qCX2kDqKEkwu3P3RvLxIjkJa7Y40=,tag:x4cb6oEeT9NbYXNmUQHHtQ==,type:str]
  admin-password: ENC[AES256_GCM,data:d/r8aAr+lOp7YlbnBeEPCBMheHOZhKvhttXnQw23Ovm9TunOkKHKIIZXHLs=,iv:TgZSEOhbFfhi4SWHk/l1QbhvtJEZLhsa/sY+ArX5leU=,tag:gIAnO+TFnUXRfLHB0FEFLw==,type:str]
sops:
  lastmodified: "2025-08-27T19:31:07Z"
  mac: ENC[AES256_GCM,data:6QUw8XdRrKawF0Yduf4gblmWL9otWFTh93n5WGEayovII3q+M0IrMB2bic/8RnhR/Iv/R8bj6rbNnm41Xr/3l6E+RVpaxZcoABKKzJcvXlSzckr240xmSdsT1K5Jsg9FyBNftu4wdEvAVzb4jQaBxYFnA/Q657jbM13UJ1ooJsE=,iv:B4VFLwELHKZXRaaJehjnGi3Ui3t549OHv3NKhHIcrmc=,tag:8gZShrK4BaMCVsq1EBzFxQ==,type:str]
  pgp:
    - created_at: "2025-08-13T13:54:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//bBDuA3UE13QEqXHqDswsP2NvsAcDVvdRzr24C4dQ836K
        hKK3ZJ1CNNAxiUWEyHv+qnygs5fgFYHnhHRIER3ZWp4Wfr7Ntxbm+IY9B8vjyhHe
        ELKgZHxG7o8sBOAM8eQoXDx59S5tY/cvzsL3lTqWHxsMAx7WKMMZwxujnEjF0sLV
        eDJRn2dS4RhZ2xBhipSea8L8kDVaQkJopRFnaaP30br+My2hJ+okfhj7VZF8h5Wx
        eSo4Zfk30fx4D1LAbVvCEt7bFk++Md301ISZ0k+hHjoc7XZOfw7t8hZJOm5LdeoX
        Zq7hto86Mh51YdpFq4qoKbn/rjx90eBRBvpsbzjrBE8TZ7Jt6rDODgfce/3z/KoJ
        fjHZGlnDNFWQOrukvyhUQF03QyOqyASYmOCIMTRewXoJm2DgDmhtKnQL67ws6Jm/
        fVxMrWd7qr60iy+EVmM7TM+Q2InvHHwzYbKJGlEvt1NSl6WRxVjDrONJpQnnIlh/
        B7JiRvusgiuTPT+Rrfz/1OTO2NLfShcoUivaNSZ/KMYKKaAQuE/iNKsWZPSkjDoc
        lgGk+Z4kc2tTD1bG+qPkFZPRY0vJjnreWf5V88hHIWR45UeXApULizof3I48SpHG
        /uPeXwmRRFYms3Y8fTOobZR+rJWSz4625+jlmdJuv1hGayzRg2IojXP8fO77F1DS
        XAEg0eGn6y7ea0sXAiWBdG1E3vk9WvcTqS1FSRmfA0SrOB2rlHiHeK7CESW8Anf9
        qfaJsifpbDA8vkezd7n56X/dUk8BCRvPYvA/hYJcKbEGHUSJKfawpgvlYEdN
        =+RCU
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
