apiVersion: v1
kind: Secret
metadata:
  name: stirling-pdf-secret
stringData:
  SECURITY_OAUTH2_CLIENT_KEYCLOAK_CLIENTID: ENC[AES256_GCM,data:jOjhmCqp+20hKyMA,iv:QyDwYsdRJ8fzhM67lCOrcj5D6hvSTLdRz0DAIvlYyg0=,tag:TswE4CnCbWi/Uxqduhfprw==,type:str]
  SECURITY_OAUTH2_CLIENT_KEYCLOAK_CLIENTSECRET: ENC[AES256_GCM,data:k41EDnWSBhryKeAOs1CoZa3GzpaRZg346g7t/yjvTlk=,iv:9R9ffzJx84OyvqP0WKwoD6nI26HUCRA9soLc1EUhQjA=,tag:DjCzTRiZ6+mRTn4+oA/L7g==,type:str]
sops:
  lastmodified: "2025-09-11T10:51:22Z"
  mac: ENC[AES256_GCM,data:E5Q3I92BIbjNbgrXTmoV3xeTMBaLk6uD4scRshL8W/+0Msgv1WbyIBWl/STd1V76ECZAw6DVAeHDrlr0pFJ6gsBcuFapLBK4NEuyGJajsJ+ZiD84BZ8mqqfnOzI1zmT1FBbf0RLLw7ICaXhlGvYZu4C+gSwhPGYdUCzePo4YH6U=,iv:r+jA/BWH1TCl6b6A4DfiwskBitn9HXPGB4RBVeyjql4=,tag:4geG3U1PQ5blGefzgWTrTw==,type:str]
  pgp:
    - created_at: "2025-09-11T10:51:15Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//UokXG3cFN4Jv8Ucr1cQHM07stcCNPMAOzFw4L1qlIOry
        O1/of4KzHORS4nR1EpVZ2Wdw2QJyupLG0/Uemf/SZYLmM92HXFDHI791Txw924gL
        cSD8r1m6xtjnDOmLKQrJ06OtmjdvULQdXRtEwHLDlhEqusln23tJEozIMJNJdYtH
        uW/PSBEVRtmlk9wHSP23S9g/M1052fKMh5gSjeQWOvAfhhUrNR4KcG8h8vgELBAU
        hkG/xY0ep2lovYGVHDSu3w8826nahaq0lyA1Sm49SSc+Gwyd15GSWvEzd+yRmdNL
        5Tvk0M1YdoXIYusVdr8VKPnVZ4khfZM0ixyElF0nWgwiWNOjByf+m4kCv0HWGHZC
        jicz1wvayKdA24CJhdeJyVZz4wdTW+DeMQAck85lkg1d/6Wrn2OVcnzfaL52PTEz
        p5mqjjMBAS9S55kUW8tnULXw7aNZuUn8VHmkpapLuKZW9GvLiH6wIx27Idj9eK7b
        oYqC9VC4GoPl08n9Y6/kDE1rVdrBtz/E7VsEHOIDJ0JKUCLLLOHQN+hoT0HWbMJk
        TbWQDNuyYH+aeSJpcYI2iwOJ/q6tcZv8qXYCbnlQghgG+9p5AkH3EAPutk1dmApN
        omN4Qww9ee5zdtgPdoik5UkPepSPV29aaaTayXUlR/w0vh5BQP+MgC1YcE45g3DS
        XAFNtfiHyTaFew+04efbvKcVls3+mSlqO+/5dGcdvcFiVUJ42dyn7X5zyISsQbbk
        t5sx+oC9sgCWbkjfA8NxnoL2p/UyRQryTPdO+gF7f64br+fUOZuAqTK8lbWV
        =6ILZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
