apiVersion: v1
kind: Secret
metadata:
    name: anytype-sync-secret
stringData:
    CONSENSUSNODE_PEER_ID: ENC[AES256_GCM,data:VmybNxKXpxXx5h+QjU48GJCPGQ6ySAm3ua2MZwh6cev71GPzxpZ6eAybVoCq7IIe9Me14g==,iv:rJDl6IYU3T2H+zW9arGoFmnFz11nfZwPXdKTf9Xo4hY=,tag:3q//Mnx3nqiz0MBDkkeipw==,type:str]
    CONSENSUSNODE_PEER_KEY: ENC[AES256_GCM,data:pGB1jqyAVOc1y6OySfEUMVCI9x88H3t0X7Q1tsOou6UNEu17nIVh42rtFb43hdmcJrIZ/pcKi7MFMlA41Qtj0X23lcJfQ14+7msQw7Gb8VP/tQpjZwezbA==,iv:YVVjhOPllr5gexf7c0sPIK9j5vXDB3J9KylapVw0eSM=,tag:B3o4LmKShPI2hKOwRon8tg==,type:str]
    CONSENSUSNODE_SIGNING_KEY: ENC[AES256_GCM,data:L9eSBGnGmhGqN3uHBbBuw9stVt66r8QSZEYvd3N/CjGb/zJ/zacPUI15vBpjVI5/YIfYxbJ3c0WBHsvPSj/rJYmUWFfm78uL7l+zVW4c4yvG5YMjklY8jw==,iv:wc0Qr0TJBhqObUunQIFeFWZ2i/jJYLn91cEXIO0naFQ=,tag:XlLEdyz3ezGlNEfBP8Pbuw==,type:str]
    COORDINATOR_PEER_ID: ENC[AES256_GCM,data:n80w+5sr57n8yqDkt1pAKtcmRLeGWaHXsIjuBxULLMN3FsxqpVdXqwpHUfAnOY8Mauk3dg==,iv:96j5tj6xSgaKxWThsN9OJwSDM6jYsfepX+6GO4LZ6rs=,tag:7YsLiUOgX2lcGz/GkCp2wQ==,type:str]
    COORDINATOR_PEER_KEY: ENC[AES256_GCM,data:6/5l/9HF3T9l5qsGYZ49GlI5R03nMt1gOO5xXYEZeK5T0z8Z+NhVzzEB969cNSsxlVC++uBPBaFIkH+SS4dayEM4cNvd8P5hT6hiO0LVTV2aJ7MqVbM6bw==,iv:+7S9PGv1RRj6f7SM0kx81MSUAPjV8nffENpCqXuUVlE=,tag:TbaGPOc2cv5/U7nOHNkWOw==,type:str]
    COORDINATOR_SIGNING_KEY: ENC[AES256_GCM,data:VOonCR0oGf0sIAagruFuhzcN3MnfSMh33NYrGKyTcjh5/+5+cb4CBrXW7/kz+CZ4t3J5GegPFvttR74W4D7+I3wX/CeAkbm9Y47QIJaBs0I2RWig/bK2OA==,iv:OlvAtNgm9T9XDRyhu5I+w1jHONk4t+8vqVTPU/2+RCc=,tag:pwHpTv5T0TreisrcWAkjJw==,type:str]
    FILENODE_PEER_ID: ENC[AES256_GCM,data:bA1Y0SkAglQDuA270HIa0+aoMP4Sp8+RzurIMWgFm2hK81ROUMHxk1t/BsvXwyOsqeAU0g==,iv:Ha7okP71+LwxvgU2XBt23Okrjf4AdpbCxDbUy6AyzUc=,tag:REtubYWniMirjjhz28m9gg==,type:str]
    FILENODE_PEER_KEY: ENC[AES256_GCM,data:5c2W1/BahO2nruDYawYYIZ5hubPcIhrSIWbfQ6OgPQUtG9zGVQlqvnpAwPK0ckmXGFxv8LtQONoqEB5xW/A9x0ZaBzZqxCuybRReI38u6ZaqETmKfZywhw==,iv:KAcZfmcEUVZGqp4BMJOTu7IdcxmhBc/NaULqVPw88XE=,tag:PVZCDAfKrncUvq001QYcwA==,type:str]
    FILENODE_SIGNING_KEY: ENC[AES256_GCM,data:Nj7lBMMsgxvaIO5A2OXZ+CSBU4SPqFWHiPoKx1Lq5s9tptaTe31J/MyQEEJsR4Hw/JkV2laeAog9v7btJOKdjBoUXmuHqDhooXhFX9AJtD1etTekqwThwg==,iv:PXVT9Ewpj3GQjpNu+u9GnElNvqMqhIZhi2sFQQOnVKM=,tag:Fb5SPwhV+4b2eNqgG4iF6g==,type:str]
    NODE1_PEER_ID: ENC[AES256_GCM,data:T0GmAuXDs0dG5g+3jwRI5qG7QMiZsBlzByfY378/cjKaigL5l9dZKz8yX4R+2PeCt0Fi8Q==,iv:GeVuH9m+ZPhRF+BxWhMf5sA17egTrmWiKV7eLcl2Nms=,tag:HufrdK3RpQlVw9e6YO3pbg==,type:str]
    NODE1_PEER_KEY: ENC[AES256_GCM,data:1dK+cGA+XPf6E0v63Rc1fQN6tHdZAi/Q6+YKoIRXsUZfl7wyUGq4WSIkAG9Rt9beSJxc+9IiqbuUEe/5ynDpe7XPxewgdAm78P19c4k/2U6/aPrmi8bJpA==,iv:HbLNq/rWsQLGS72fER6psZ6rqZu4kutJLi9JJgKkcRo=,tag:cl7pkYgsTLBmJ3+YWBtCAQ==,type:str]
    NODE1_SIGNING_KEY: ENC[AES256_GCM,data:M46XwwJK8Km1gnilL0Y2JDy6DpHf/H2qa1Ru/nwrpEUMualNKk6ZZxn8/JLG/NA8Oh72ri+sqhjiaAQQvvjceZZKJJLPuTVWXIwxk4joL7RMY1wz3P4rKw==,iv:Wf3PEF6J+JryUEMl1qZI5vN8n9pjba9XSlyFdLJw9pI=,tag:qz+Ars1cn3B1LN8HPFj1kA==,type:str]
    NETWORK: ENC[AES256_GCM,data:lPyjerW39NfBwv6Cajj7ymshQkL/30L2,iv:KdhwcW1Pdly4FGR8EwUIKvFcJK+NXOd2LgoabxXkPiY=,tag:PefK4VwS1eO29salN11Yww==,type:str]
    NETWORK_ID: ENC[AES256_GCM,data:6MWHsTBdcyrgWGwIW+sqgIUesTvlb3JjADmfaVuxcZOCBopUkoEV2qcfLZcBj8Y3,iv:5ZF8BacuawEwMl6qp3cgDySYK7KPn424rmIDO7HiD4Y=,tag:UbkNbwQD4V9/Y35cqofe3w==,type:str]
sops:
    lastmodified: "2025-08-20T11:15:53Z"
    mac: ENC[AES256_GCM,data:pxAfMDNeFWRIVMP4YXIT9jTLKPBhkQ75uX2ug84eSwfCmhXsGi5fLejYyVgylg0PUeXF58SLaNfBAXqcgR041sygmCMTyNmPFuKbOv/tWtpUq6Fk2bEvvhXNMHwL3xyyWV4kmkCOWofgXJ8BAhd6rYLhKXULozXVN/gj8dXbWJE=,iv:Lt4KrPYHjidNT9Z6M7Oda71a2Y+zG4rZxw9jKwuaiVE=,tag:CCCuKSC47J1FL5uCOMH4SA==,type:str]
    pgp:
        - created_at: "2025-08-17T14:33:46Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ//U5KFxMr295mCXEIawbYkl3EmmUj9fDfxom4e0Fu7Aszb
            7O9IxDqA4Gtd6syU5eRCLrk0iNBl/hD9XkWo7qC2WasiBI9p6JHxmIj2NWYSm63w
            vsIx7/UQqZeW/GJB6JMWE4ac++8xBeV9Te0kEUAi/JG+hATH0GEgxJW+cEptQuCx
            4hM0Q4C/ykblWCQ606yt+gh0gOGb3xd+exaGIgxF6gnnqQPft1SpPJbLjpXyfAhr
            AczSPMU/on4WPM0uuSTmFgfeNpo7BI1NBULvJFDVPoB+67K98B5i6fB+7/RQpZ6d
            oBgEEHsgJjY8cTeHebTlxqsBoqKd07DURbkZAwglEz+UKZrIUtcJEbGmOse7lR7/
            04XPowtDH9qLA7b3VMzM59lOWX96nD1fHg1XIeRBvQA6GRgFtass2kmRvy40G+Up
            +jEMuxkzYdWvh2kxMx6b1xB9Qf5Gsd1NuJF+EfZiLnxnuq+S/7LhiiVNLPSUWHrI
            qJO5PluyVoWCgxLRCh0YAqQn+2viC445ZbjbK5cmxzByos8CcDPbfomga1zbWdKR
            hczxjPr2Dx48wlFOUh5RkdAQaTKCf0kkErq2MWHpS0ElhjCfKoDo8p/klcx8uTpg
            aCeUM2FCpxVf8e/MCaIz1xR+cDZ+4ZIC1Z0ZJ+/SEg7S5TKiCfbGen7xuKBDfPjS
            XgG7udXfDOqYiXHEvEcgBI9nprR7traV14AnwA1RszlpaWXinh5ZmbnfKj6tFbXi
            QZeam4vmFpEBONR1s2M5DCudsamcxsnozB6uyiyVaTci+lrVrvT8C0QQSuZ1/8g=
            =3dyh
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
