# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./repository.yaml"
  - "./release.yaml"

configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics.yaml=./flux-kube-state-metrics.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
