apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
  values:
    image:
      tag: "2025.7.0"
    cloudflare:
      tunnelName: homelab_ingress
      secretName: cloudflare-tunnel-credentials
      ingress:
        - hostname: "*.${SECRET_DOMAIN}"
          service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local
    replicaCount: 3
