apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflare-tunnel
spec:
  namespaceSelector:
    matchNames:
      - networking
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
  endpoints:
    - port: http
      path: /metrics
      interval: 1m
      scrapeTimeout: 10s
