apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
spec:
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
  ports:
    - port: http
      targetPort: 2000
