apiVersion: v1
kind: Service
metadata:
  name: cloudflare-tunnel
  labels:
    app.kubernetes.io/name: cloudflare-tunnel
spec:
  selector:
    app.kubernetes.io/name: cloudflare-tunnel
  ports:
    - name: http
      port: 2000
      protocol: TCP
      targetPort: 2000
