---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-memos
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: rook-ceph-block
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      kubernetes.io/arch: amd64
  superuserSecret:
    name: postgres-rxresume-superuser
  enableSuperuserAccess: true
  postgresql:
    parameters:
      timezone: "${TIMEZONE}"
  monitoring:
    enablePodMonitor: true
