apiVersion: v1
kind: Secret
metadata:
  name: postgres-rxresume-superuser
stringData:
  username: ENC[AES256_GCM,data:G+Vq6tYrXmA=,iv:OdwIrqbtv6McVK2ENWdSvHwzr+9GeCJ1yr1V5os9YAo=,tag:bxLbcYjwmuAbvMmEhdKy8Q==,type:str]
  password: ENC[AES256_GCM,data:5LJJZpBsLtmKNWVYGxstoka3HTMbed3FT9BaDjszvOM=,iv:jy8xqxrn4vAlfihqrYJxEdfs4ORAviWazprpG8YtDoA=,tag:HLG3GItn7YI9jWzGc8pA4A==,type:str]
sops:
  lastmodified: "2025-09-05T17:27:24Z"
  mac: ENC[AES256_GCM,data:qRG9DMWQ9FqOGqzYgUjZqCJWZvS9D6NEf6N+FxV7M+4i8HQNRwPPmdCbEqPpGB1alczIO78UZd97vHelug/hxmZ7+6MFxnfY8dwXCZ6SATkFgIV9UqyZYz5L/nUFAVCGJ+KdWzkD6HNUjc6/V8FMLbgLen0oYqXciA20s0g8LXY=,iv:AXjwwfS4tQllJBixdVCvpGLZ/O2VUvO/1matLDzlBpc=,tag:cp+Viq/j5jwGZGM7XWs0cg==,type:str]
  pgp:
    - created_at: "2025-08-12T14:08:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAjJO1d0laKZOvpdXRf8OGGK8ZI5XEPfUQaZ916rCuQdv1
        aOuonuJSEMoUQyJ1L3mogR5R3GijZeTz4PtILSPhmGoBtd4SDhoXE1xdk00dQQ2c
        YVRBegnBSi2+ofaCU2oZvwiM5Ut5TcmsB3DewNuFsa8GMh/OSDyru/dbPm7A/WQc
        /67/OunSn939yvaLvN7U7MGyJdlZnAdtf9+vhifFJWOfvbmcwV6cpkg2bSczSdwc
        bGn3S2O90wv4AgSACyf1QgfmqenRhQoQy3GrFC8Uco5F46QPRz/lOhbdm7aWw1IB
        dIEF7RIZ2Efyswl8oQXxRkOlTuFV3sCbxRTD+POeW4OmyWO/326JAnmRUzU35bQL
        ISp+Db7X5dpJ9Gn9E47ze/dYqnltfHcjGZzFV836/OgvLA4Tu9uYxNplXnA0MGFu
        25X+deN0HxRTil2YyWsvPHjwWPwlOV9ab7119zKwAatTQkIPt3xBpXjiOmDCO5Xd
        BAJWxgJY66ns9kXqbP73jP6NbKXLSM8Uju12+NIkogD3F6gtOSDnw34soCVT5/p8
        dPqXPXHIdaDT6ASSZPoHW8IGIxQMwqNZjZcW8czHvzSn8k7sjwO5kDewQmb+xFBG
        WTVU45ZmYO4cnuj39IcFTl9Eb7bvZ32DWb250KVqAaUTEWarO3tdVxwTQFA2nSLS
        XAGMPRcOnhlNRI2ZmfFtl7irro3fC56SHgav1/ApcSMb+UpL7QbalTcKbwEkOZcl
        mmPYFP2YjdCHqAGCmLoF4WljYS6cGTFFYqqkaiW8VkygxEV2K/0W6DO2Gvxa
        =uMlZ
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
