---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-prod"
spec:
  secretName: "${SECRET_DOMAIN/./-}-prod-tls"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
