apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:htcdHopZkBFi72QQlYLROebAPGgh6kmG5fnI7tAhgdg=,iv:A0IHMoA+kcIcDaeyvjZygTIQIREktxo7ihy1PUkddh8=,tag:sM4B7Q07GilZEooU+WFzbA==,type:str]
sops:
  lastmodified: "2026-02-27T10:59:23Z"
  mac: ENC[AES256_GCM,data:qzuvHTyp1rshAHBEWfwpovcCfLgg+ecc2L9CIA2J++XAfjTA9R4EVUaD9MOfRcBjccbO3TXaswylL77nPhLuVfmsFpA//Bc5PaSiYVhKZwWV486UvoheQyWzGhDzKl2nTsKLDVYxlVoLXdRWcdv3vQWwoj2r6sL/mBwEAOxT5NE=,iv:Bu/YfVKDeqwivgNkEyd7WSRw943R+gM645NJbR6/6sg=,tag:UQzzgsFw24C+bXAY7CVbsg==,type:str]
  pgp:
    - created_at: "2026-02-27T10:59:23Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAqe8gMXHz7DhKQ/iymrP3cxJRph3JfB4qNGknezq3udhx
        wc3oK32bUYg0L3A2aqt3Kc9jqiIn7XyXHS/x1rgdlP+tGZTOiI0wsnJCzz68Suyb
        iwrl3mb/6n8P5RlaweFyDIJ2dVWA7ubarqYKc+ehRxLH9IktG+JDn2k2P864iIkH
        odlsqh/dCvsR8ZyL92PDPFCjFauQko/NT0fqafVkefavajB6slSvnj5OmuRe11vv
        O0eckiJOocwvnvJ7qJZZMIbfLaW37oK7vz+xVayUN/5TsjMIuaQ0M43SXC2EnEms
        7SlkoHYDQkBO8adw6c+qpNbZ9bNBFTJuU5Xd4Ve/psNqnLp09waWmKwKnixOHIEM
        mLiM4Ms1IS41dA0uTUHB4R3bpw3Q2mSED8zt/VB+W3s+DSrSYCBYwGtBDsziRee8
        q/SyRaMnb60XcI5qcY56yW/Me+I2nuwxGZ5wevAfxmWzExrcJYeSqwCj8sVHS8wu
        1tLSoc3W5N+RLZPYAxKZpHAoKRyw8dVHR9uCJM/+/pZX3Txee1ssLfCk1MOvigUC
        PozaQKNCVFLlVTWD+tuohX2niKujM7YFLEPOFfimqAwH4b2etMSJztlsFA9DcaQ3
        NuBiq1cE+b1qGPCRgFT4OvhNdqGad1huhfOg/49/bMtfB4yJIDdA1fmpd4ILHurS
        XAHic/xK9K3nt1SRtjIICe27p4vq3LXSgOAzieQ4df78wSx9ZOoOdrYHxTnyyFPY
        /7ZvtqoIy8+i1wYlW1dC756NKZsEfi9qOEcbe8XhPoKnUJPTiDZVjBUBEu1r
        =nQA2
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
