apiVersion: v1
kind: Secret
metadata:
  name: metube-gluetun-secret
stringData:
  #ENC[AES256_GCM,data:pYPkMtHIFuJhpoQivhdgg6ngVVQ=,iv:4pTPphXKUp3A14JKOFgSxEXoP7YrX2mvWpbhAqy4Ej0=,tag:LQKktUi2iFy/ILJKFmhFQg==,type:comment]
  SERVER_CITIES: ENC[AES256_GCM,data:m/ia/lCY,iv:8MXDjq3oeJZsVXHR2mLgYvkD25slriQwWLTBQ2+RhyI=,tag:dchgjjVuwzhovHUr+PJQ9g==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:14B0iV437g==,iv:FQVchTF1j5iz6slHDQyrwEweOQf3DhmjExuXxHHoAL0=,tag:uXDzguHC83BEBuRmQBFxjA==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:jrkhCAVT5A==,iv:Ur1rPqA3luv/RfwhSb336gLutmsbKWH4VjteTgeMdtY=,tag:XSwoiiXwSyHCZV5lMmg3Iw==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:S1RgmlcxBRNT,iv:yWcriSMpUc0zTOsqdb9nDK58h3j5/ohX0CehSq0vG64=,tag:4w8QcHiCVd9+6rGu1s5fQg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:OpS7TrLcPD8UmpxqdGGihLdusp64Ywbm4BIme1HEA4VltZOFYNxR92mPlp+n3w==,iv:a7QwdFrpu5ZqcGwIpVm0hEmUzO+6xJ3u/M2w9JCeU6Y=,tag:Tl/9itMRiO1WSvWSF8qonw==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:RFUT069NcwiHJRt1klBh0xJJ+rqt+Xhu3390KlzCx+HVLIkAeQAEtENpd0U=,iv:f3nBpoM+jX2CI6HnxzNpiZhlWTa4BE5+jF7X+pQk3SI=,tag:VBmO00QsunGTlaUgjvQnrg==,type:str]
sops:
  lastmodified: "2026-03-25T17:10:57Z"
  mac: ENC[AES256_GCM,data:e6GoBqG+njKD8KFOwVqsfD4UzV+Id33erACbEJYEIoBwY+aSnZ/agh7EtPkR97eupxl+1whTaP8Xlkrc9JpkfUAaYPXsni8k37aV+Y/WhmgW/UWX+CimzgIH3hFjeQDEGbQg07AEMD5MgBg9mswLSO9ujPlH2W4/NS20Y76Btas=,iv:yyHMxgJEjgq2sBMUwwK+Vva/4+5tdAkSEjaXEHQTYJ8=,tag:3sQRPZFXFWmn0qGoEQt4MQ==,type:str]
  pgp:
    - created_at: "2026-03-25T17:10:57Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAgd40oIzNbUdYUkqN25tCsBGerjs6/tVSk2qmchS981UQ
        YolViopV7vYAmLD1NOQQHzBaxf4pKqo1Z1B+N0PYJF8dKEaEZnsZIlSTKHH+leLr
        NZAxJJWIGciPR5O9eXavPsA02MiK10JbLmL0u10sv3HYZZX3q8VLL4smt96ZPeYj
        GfTF1mfBOAjxkyb3gn7CHf5qM9XK4Wl+ArUvK58U3pxBuWNNfjWCBAJthr5Kiwe1
        6i87sPYxmeWnFAAkV/KP+kD6Pzkn6M8NAQpxzwApxbxF/Wxz4OIEW/a3fzVfDErb
        1xygI3OdVwmZXbXsLnv03PYr77WKI/L7/3sT9g3ziCittHAcxv90LoQsn1u2mmfL
        Dhk+xfG7iSdmKJrZtDytmEBxDvjM5I1qW63v7YeEMtQv19Ao4C90Zj69xJCLzMGl
        DGYtF4yHp/5Ygjwne+UConCZ0BhR+25mxCBGv1QbaiR6nbwS1I7pXrWTupD4ktM/
        KNjjLWaL5Pn+caaoiMgC/oSfBz6jN/Ax6M5QPE7fRklCsamfODX5DNC1IHhlA8Jf
        vQT6cfn5IQC6lbIFVnm5tUgfcGL6mpzqwFVnvM/GHobC4Tgj5+DnqOF66nbSTuzH
        UvqQUOWcQEixg6GRTusq3JaHns6M9tTGxJmsbk+mnvS2dONkCufPVhhTELpmX0vS
        XgFvYL1H0wKg1vifRmHgQKnJKQNo5PZDkPQtgo9L0wkLlIj9qu+TPldk6+v2UBd6
        k7tUF53S5JuBjGQyCXI4CpUdhg62miXjjDxgJ5PtpkqlvRGGfhoLY96bHGdPWRk=
        =3Ek1
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
