tailscale_authkey: ENC[AES256_GCM,data:o2fLk1KGa84b5/wKl5aIt79F4rLXUmUHIUwjxYxuLP1AJLYsQ5i7wp06P7B0+SYBYlyji04okinxbZJB7w==,iv:4Ack6IbiP6y9lBQKytAg/Ne7dL4KSIAMDXlMhVskCdo=,tag:PTbIoW+fyPXarZxtmenujA==,type:str]
sops:
  lastmodified: "2026-04-03T16:43:25Z"
  mac: ENC[AES256_GCM,data:Gx9Z9OyiROO9stObd5CxKfh1jODRkBpUnc+X7oXYcspooh8q0XwaDAOa6YJIS8b47nsYjvrHUi2CASBasBEWokHICTjVBrf8Rme7lmlF0rOW2nLit2C+iJGq13PCcxleGMGJ+k+RdHpSyROgXAfVi8aniu9msLhUBlImeq5ilU4=,iv:/OekGt2Fxa+0n9JrPat9Kq1QYT0GTBPehpg/8Ka6t6c=,tag:wNrI9+PI9MSeOql75IXACg==,type:str]
  pgp:
    - created_at: "2026-04-03T16:43:25Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/+JMI3EseoJnEnJRbgue3qe0fVuLW4LwRnV5PB3Vutu+MS
        ROVbDpPKXMq2WJFN1S7sVQ+LoFOlrnXcKelccR0PqUtHi+jwQdHAigkIKnhGOlxD
        KzRutfQC3uLuKRbf+6ryS25KBEd6CG4q91K64s7Kj4mgdlRSiJRX4JGqT98rVKow
        a4c6zJ1NexbCFVWBlcTdPcsU01FfIlkb4qyx6FVx6z7zc9dHYrVliO7EejJMJItg
        ncbmDoKX2ZNU6DDU8R5csZxXQ+G0i4aW/+t5EesCX8J/w7Zl7LHx05umucAjkned
        8bupv2sIX1gD73EoMYTk/P3dtPjtiZUdNL31c6COYI41pr7R+ARnmoWA/cFFzaP+
        mRsOaTeo6jEpmuk8BqVgSqa1QgAFac8eBkDcVJ41VSQ7+o6BDDOW0xkegxoXyiJO
        925PrR1pynVrmw8VkiJkv6jYbkMgqVYbUapiIiq/8XqUQmWeRcDC51Yq+JywV/ZA
        YfZbOy1i/okeBLfvlbT8BEunsRSlVJCvOSQwfPNrD/OBQQ2Sxzy2lj9uJnFY4j4K
        aVjrHdY07WV4xz2rVjrxBrC9qJh++crMHOtcLxgSTCsdiA+yjmnrXw8BbIvXwvdq
        mQlO6DVSOy+L98ZWkbXNhh7HtebMZNugUzCCwFkT0kpSXHcl0wPeiMWOARxKI+jS
        XgHUPmOpKn72/fbUW+dV5BMglV4uQnSQlBEXMDTCmA2QjJHp32Q3ssmSRPWR+t/o
        Ep0bKDsSimQZ8Md1xgjGUeWMO0ISoDzqaxRnHbGWn5EdNvHQz6r998RGYxhIyKU=
        =Y3wT
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  unencrypted_suffix: _unencrypted
  version: 3.12.2
