apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: default
spec:
  chart:
    spec:
      version: "6.6.10"
  values:
    nextcloud:
      host: "nextcloud.${SECRET_DOMAIN}"
    ingress:
      hosts:
        - host: "nextcloud.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific