apiVersion: v1
kind: Secret
metadata:
  name: linkding-secret
stringData:
  OIDC_RP_CLIENT_ID: ENC[AES256_GCM,data:Z+JO6zPyLW4=,iv:ek/wOGN2WyqWzouJdQQujMmaQU35+2+RfxlX9O+MOlI=,tag:Uva2jZQ3T5+a9ciV4wkl3w==,type:str]
  OIDC_RP_CLIENT_SECRET: ENC[AES256_GCM,data:mLBNcUslyo3/1lJs6StDPtc2p3xIRuOA6wyiI5mWjbY=,iv:Fisg13lw1YZFYQpSljONsuH4II4ad7Mh9yoQ2X+vLyU=,tag:G90j+QEk41bKJY4SNM5YBg==,type:str]
sops:
  lastmodified: "2026-04-08T13:17:54Z"
  mac: ENC[AES256_GCM,data:qOpz/ABsIyDEbW6ybbyQVSvYDtCX17T/OvNF05MPLJk1zDWK3WbEJznGra3fD69R9WCtN50NNgoZTbnKlPL3ug96E3rYDsuJHXFQRHd6PTJr33T1Uf+tym2FhFo3RkOe7tskXkcpq9Io+Z2ZQVkjeXWlAhRGsJaCjpVu9LxWPbA=,iv:Aph6VkUsjX1Egs1b8diqFi+PsZQfYzIK3CN6p9OBW/Y=,tag:qcBTVDcRNwTYi09sfdo4fA==,type:str]
  pgp:
    - created_at: "2026-04-08T13:17:54Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAkDhZyfMX+WBAuEo8C1TqEbQS5nA68L/MUW4cZC9/wy36
        9jPLmD1MLDAMyKAbJiQ3pYfS/boIoOTnLY+QGhLfyQYCrHLguUlpk7N3DjvLDj3D
        EzrHrx16bPfx+vAT7AOPvDg0pEJU48RoHwr80zPdSV3o6t1+NIOlInIBrgh9ZJuZ
        odpFIEGWldwfrn7PH5AFjvJ1dDaiIsgfzvobzqIdlBPolN4imd9yFf8br9p+h3mg
        cjqEvIdeEDQDqg6DTkJMZq8FS4u+JliSCBFX35gfH9tH4sKFB41GTWjfX4Arty2c
        PhSeL6V3onQKnCUunnwKywyBA7Kr5vjUvGwj8+RVZ/YjExelLsQHIQdPnZEk1Hjf
        WagvExxcENFeQMVb8Sl8L6tP0c+vAvFgDA/ofxugAtG8sOKUQHRTN+GqiTUXoqNN
        qJCykjM2kPjMvLRNLKsR+Tg73kv/+5UZV6NK5BDTu+U/2zAlnoG5OBauBgMTMQ0B
        B6txtPiKWiofP3AfH+804qKQtqq8+NIjAZTc7M2TbmnKZ2egBSuiSngWZ8eNuiQI
        /vQfHH80+RLvT7M07XOpEo8I965nBn20ONBssONU4MUdBJkRAtE7K36cJKa/uWRz
        kQUWvbxqvQDH2aLmP+6ieVIf+TdH9+3Fi1Tohbi2wDsb5w7PVUZChIP/d4eH2+LS
        XgFBBtqlBU/n2pA973UrhXmOyLfs9YCVmalfNPyHLI86uh7c9EBPZZR6arpdWJ6l
        VzJahP003XKtCMDFk3Of32jr4FU2my0IIs81edQyZeu1sa7WhXfgLQy1x01spzg=
        =DPA2
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
