apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel      
      sourceRef:
        kind: HelmRepository
        name: cloudflare