---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homepage
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      homepage:
        forceRename: *app

        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.4.0
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 105M
              limits:
                memory: 225M

        serviceAccount:
          identifier: *app

    rbac:
      roles:
        homepage:
          type: ClusterRole
          rules:
            - apiGroups:
                - ""
              resources:
                - namespaces
                - pods
                - nodes
              verbs:
                - get
                - list
            - apiGroups:
                - extensions
                - networking.k8s.io
              resources:
                - ingresses
              verbs:
                - get
                - list
            - apiGroups:
                - metrics.k8s.io
              resources:
                - nodes
                - pods
              verbs:
                - get
                - list

      bindings:
        homepage:
          type: ClusterRoleBinding
          roleRef:
            identifier: *app
          subjects:
            - identifier: *app

    serviceAccount:
      # allow scraping of k8s resources for widget
      homepage: {}

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    persistence:
      config:
        type: configMap
        name: *app
        globalMounts:
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
