apiVersion: v1
kind: Secret
metadata:
  name: readmeabook-secret
stringData: null
sops:
  lastmodified: "2026-03-09T17:35:59Z"
  mac: ENC[AES256_GCM,data:1y9na6sfw8pMXU9U+ldN6Aj9hNOV36SzdJOxuMeb2qxSCvS6M5pFyeKEMebAMHYK7ZT8EqHYcdjs+HwYxdGiAvvrnJ89RHFamQ52k5ZyIOvxC9Bia+8zNnu0bbfFqXuUIl7Vwc6/Ppie5ApzBGCBaLib7yUOFbVTtHWwfgJcjHU=,iv:JxXjS1bI7QFCDYwL3U7cRaFHg5x/PoaKX1YldhRKDVI=,tag:/ZRAOzKa9ujk7D2YjyxVPg==,type:str]
  pgp:
    - created_at: "2026-03-09T17:35:59Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAArTt/cnSXzGku24NKufrXXgPVzk8dWA8raEZvPnvVTNyv
        9dntqwvADg0MbrhjQ2Pgf6o75oWerqOPdGALvs/QlaMyUkufEYomzfS+toekjYVY
        5vzR9Y7R6HXB8tjX+xLgd6HwxZrj9BUbehKpGny9pTWuGCVUMYbydD2kIqGiGZar
        Pcul+fmEc4ahASgv1HwI43k2WRfUWRP0xU05OOtH88i+LDUhKp71aAG8dTvQwbSy
        OZUdh664XvotJpRTHUIULO1fbFkYwrQO1hkqEAosytxqeTHi0st4FFCs2h/0QsQX
        Fs4901+BPiDGbnraSk5bayWJgSIc7KPiA/xEbpWW4DFahsyQZuQQbBFCg7rnoctP
        JBdiZjHD1/tjuvqHXL4futX+e2GQRN/VlN8MwhjNAMh6+T5hl/RweINTcbVSkwU4
        YauvOgGEOrMTVGE1xhkDQ7ghRFwUEOa140DcwLxZ2SWfzoruXexFYMDOKoih27vz
        0coA4/byK1Ss/Mvx8CHBpgq007Pi9Gv9O0wxJz5IAxin0spjMAMKKARfDCv+Zg98
        nYjzti1QCTI99TW2PI4aE4xab7ZCkRhdh2UaC1Mifcch8sP6wYWbba9Oy32o0QUa
        RgcQa9hTS5ZyT3jujbscMwX7BeEJyijGl0vjeZjWhus71M091zN4TYVRxZpv54XS
        XAEZ69mdv+24/3nNx5HmjpN34W893tBacHT12B0dE3OTL05QgutZnUOUMFqFh8pv
        Otym5hHwPqfIvBXmGdzksy+ZzDnlkN1jbWefxt+SZF3MmU6/jNCvoyOm53C7
        =ULyE
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
