---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-affine
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: rook-ceph-block
  resources:
    requests:
      memory: 500Mi
    limits:
      memory: 1Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      kubernetes.io/arch: amd64
  bootstrap:
    initdb:
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER USER app WITH SUPERUSER;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  superuserSecret:
    name: postgres-affine-superuser
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
      timezone: "${TIMEZONE}"

  monitoring:
    enablePodMonitor: true
