---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trilium
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    controllers:
      main:
        strategy: Recreate
        initContainers:
          init-permissions:
            image:
              repository: busybox
              tag: "1.37"
            command:
              - sh
              - -c
              - |
                chown -R 1000:1000 /home/node/trilium-data
                chmod -R 755 /home/node/trilium-data
        containers:
          trilium:
            image:
              repository: ghcr.io/triliumnext/trilium
              tag: v0.97.2
            env:
              TZ: "${TIMEZONE}"
              TRILIUM_OAUTH_ISSUER_NAME: Keycloak
              TRILIUM_OAUTH_BASE_URL: "https://trilium.${SECRET_DOMAIN}"
              TRILIUM_OAUTH_ISSUER_ICON: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/keycloak.svg"
              TRILIUM_OAUTH_ISSUER_BASE_URL: "https://iam.${SECRET_DOMAIN}/realms/${SECRET_DOMAIN}"
              TRILIUM_OAUTH_CLIENT_ID: trilium
              TRILIUM_OAUTH_CLIENT_SECRET:
                valueFrom:
                  secretKeyRef:
                    name: trilium-secret
                    key: TRILIUM_OAUTH_CLIENT_SECRET
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health-check
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health-check
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
    service:
      main:
        controller: main
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: "trilium.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "trilium.${SECRET_DOMAIN}"

    persistence:
      data:
        existingClaim: trilium-data
        globalMounts:
          - path: /home/node/trilium-data
