apiVersion: v1
kind: Secret
metadata:
  name: trilium-secret
stringData:
  TRILIUM_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:XycO9/aPTTkosA9EuQ8Zv4vziEiV7+clTYQXemqik9U=,iv:ug6lVdev8iExwkPrxe9E6m32/+nYSaObaQE3bI8W5RY=,tag:8l8IifaidSWPrXjoA+aDVA==,type:str]
sops:
  lastmodified: "2025-08-12T09:50:58Z"
  mac: ENC[AES256_GCM,data:f8SgBReyMW8wugzhq2BfJmBljwBXM/uJQr6WSh4xYdPpW1xgqbVcn3bFHEnA2uP9qENl2xTcY3W9tzmepTfnhR69KoOCnsxqQXmUoaQM7Nff820ywJquLhnV6sXTJDcz3DqtF38MkCJ4k3HGGurj259FCJSCH8dI/s2law+MoGI=,iv:BP82xHgXV41euPTMKy6gfYUJkndquAsnbgh+fDf5AvY=,tag:Pmczz2+EUhIncVOL+9B6bg==,type:str]
  pgp:
    - created_at: "2025-08-12T09:50:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQILA06fffInlMOLAQ/4t7e9iLZfm0V9Hyv+J9yOcDscV3HQQVdRYbI/O9FXmPg6
        uAayi3jzMZ3YVeQfGlvt6/zl3iTxdYv94Wvi5ReMSTzfqld/CgrHLe1c7IDgbUC4
        FWCC2pqK7KcD5YwchldmxoXX6vFKPEYJ8JmuR8OnTKTRsmWdo/oQd5KT2rP0+Xa7
        H88VFB/ln+QppZ0iQAI7iXDdLy9q21mwwZ+jj7vwKmFzfz5FGJdjhgQ8b3NMzFnS
        7kpEa6gHHFEHaDgZw0rxlOrsdZfvpeGr3qMCIoXUsgsdOI9K4qkAD/BVOZ7eIStM
        xfens/GYT1QrN9jHV6++whyiayaPpaTl/Xf6mPXMS+OLgeJbdSxOFRZYI0sjhH/6
        R/Kn7Vlrds2rHqPVAzD9uqChdlCZrPLOm3Q4E9wa3nD57tSC1t51vaKWJGzw8nuI
        /gyqmXLYotzALCls9BZVQ369xpK48sqru02P8vKehneqMBhICYN4YUQBw+AKwQ2f
        nwCdP0mzpo/hiyfU2hG2Gt6KgZkMCOtGP/5KesXMXsJwq419Oyjuc4JXp6JrMRSA
        yZyFgib99hhdJgV7DhPRNliU/C2JB51ZzzKOtxMy8G7ua17OJSyxSiPWVqd1/oDc
        N5/fFxhiolDG0UkPwhUJYbyEMYmU+/nho/Z//hVaC6bRKgOUVdjx8U0YH/h8YdJe
        AfO1MtmQHBEsS4alg1chW8XDWjsTNv4nNNXB7Ti6oiejpamvnO0vMB3DfRsmchUq
        HzYj448Dur+sJ2hiTH874vv4FQPZjM3I2FIJxAC8XrAJANrxa1HyLhrZsjEkXg==
        =jAzk
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
