apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  chart:
    spec:
      version: "1.17.5"
  values:
    nodeSelector:
      kubernetes.io/hostname: tc01
