apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cloudflare-tunnel
  - secret.sops.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: cloudflare-tunnel