apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-credentials
    namespace: networking
stringData:
    credentials.json: ENC[AES256_GCM,data:WjnDAwtBsCvVOBOf4skit4nJFaJjC9U03dFGQfP1D6WREYPqKGGRQLn03QA7+u/m8uqngh+Fjkr51k0XK5mJHni1ZJexlH8pNlESHViPQ8BMGFdwBH61xiqsiebyTdctSwyBuERkyfh4DImkTPMtybOSkK0WfIyJBzkz7Z9Iig+X7To3qpZM7OkaFbU825971Rttl0xP0lT1IFPoOjFyY8fe1Gri8zhmK3qoyhAM,iv:/5U/PCK1KgZCEtIz6zdO8rbIlwMFGyDA58Fj8/6FK48=,tag:7f6sNKUECAFUDXeLlZM9KA==,type:str]
sops:
    lastmodified: "2025-05-04T20:51:56Z"
    mac: ENC[AES256_GCM,data:W4CmTjG8Buq4KoF5l31UW3dBSMhfh6VkpOxoUfR4Pjl0RzSHEus5kaQPuBWZ94N7fI1aEOAeqYwu4NeSXWHHRrfMGFu8TcE8Vp7IfXfi+AbG0/CHAlCLXhAuBh8s29NO637x3v0p9y2ktlsEuM1Mp1LO3Iy0wHvgY8vsrw9W9HQ=,iv:JBJnoelDIWyabhDycEqMDi2FzuT4RXlM0/r9P/X+MC8=,tag:UHPyYqUooFTrUBxYQ1FUpw==,type:str]
    pgp:
        - created_at: "2025-05-04T17:03:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/+M8HKW5Xi7slQQPl18HANrGhuL1B2yP6trFRVsmILA53u
            qvumWYHNVhRUWxY4TF3SAPbCYQp0oSqnct8r3hBZ5kHHi+BsoK+BSRD5D9VZDeqT
            ScH6sl0G6QUDKgLmdMCxAssu4keFT2Q2WQdBNUs8QKq28KXZn/vxvHF6XAGeRX3e
            odn3jQxKIfn6Z7aUy4J7ykWS/k7GKFFgAS3fz2TMGvZmBUgFmq6qTjZYRR05uAoc
            tTmCRLXvcuTkDWdj6dFEdMKYC2rx3EfmmeaXS7Hh+2pI4cJtgQ0OR14LRGKCX7YU
            3FSx8I3iAKKueEi3vA3BcrYcJ1PMDY8QAm8wcAu+TcWlqczJ6Wf2AfF2KXxnq9lZ
            nXuqZUK0trPD88eQfq5tqhSI1xJqYK9ey6xY6aFT/8SfpJcgnzY4PYi+p7R5arnr
            L8cW9XDVYVarmD3O1mKfDTlWfkaKpbhkpQyKJkn7MHo1EeBfk8dQKPZcU3kC9BQd
            8VSwvQ3vF7lqH9nc4NSeGSwwqA8kAFGbklK7WsXL/ur2QAENKyB2Ip3bAyroDOTS
            qrTzHmE9/KkQuOPHS5c19V3aEVX6MzMIM58ZqIhNyMEyAcqVVKmGQgwVyiXUaK1E
            4j9YKV/1M7VUj/z5fT8av5gB42o1K//9L2TsWpY33Rov68lWDN1I9CxPjUmM9bjS
            XgGQLRZHB89cQvsI5tcAUhAeN8d2ccHmpMo6sC9ItlG1fphljmajJIYU9J3PnXWk
            Ln0TqIKvpNOxIiA9r4e7qASNzAEotpTNVKY3LNg22oKNRAg43N1Y4EeZFY0qXbQ=
            =Eeod
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
