# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homarr
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/homarr/app
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
  components:
    - "../../../../components/nfs"
