apiVersion: v1
kind: Secret
metadata:
  name: mathesar-secret
stringData:
  sso.yml: ENC[AES256_GCM,data:0ZGzA8L2/RkiASOOsv33brGITj5T16Hju4k2D5fHwNTiuemtT5g8qWiqEAMO3nls+Fo3hVcQZLV69gsYCPvKe+992xeNFiVhhMaWYxYQe6ZRNztl5f6+1vrZhTUN03sCmhCxDs8Kzdch5+mN2c7gNQUqhqBTafj379Dpt8GiEdep7HQNg3RJ0vxxpX+LpvlGwK/jdzUTmALrCfnByQI/JPrz5GwCmfeiaJNN4rJetL25iNjD9MyCLcEuz37resGX,iv:2GvoHdKCCjI8omnSLkzn6d99hV3oSmmq1ZHY3lMpkyc=,tag:8GhQ82WslfBaGQf2ZJRoRg==,type:str]
  OIDC_CONFIG_DICT: ENC[AES256_GCM,data:WpufLneyvXSaB9F+ObWtbfSgyr8UrsQswBL89vNIBwdOqHPhjBa0g8XKuvKWh/Y+ZI1ik1/ZwOi4VhVUGgeQX/0ATZyvHL0qfDmo5UzjUk23MaEAwZHsM5SofyQgEdQKnCyjYikhgMCT+ICMXY8YsZaDDcKDEk9F5W004ZXCWvPpNBcXZfcjfNIUJdO3KIYTiQnwmHT9QcTQbfH4KdYO8pxw0prN4ey707Z6shMegfda8kM9UgCIWgxQPcKrlU3fbSPlFQWTS/785futd+sma7EWvJvJsluug+4is2GCZor8mg==,iv:TrFvX/gsmb2hwLbFn9P5HKVF2SsP5XK4Hu9vkEghuYg=,tag:L+FIpT5/uIklhr9HJZ8RIg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pgMVJaF3n+AHESxjI6Gmrc5ss+U=,iv:4wqTczRmRyYp25oSYZp7SW9BKpdd12IxCdqtygmgwq4=,tag:lZd4ibpl1DC/fFh4wDr7lQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Z4DZhI2FUdRfvc7dakJUZmshd0XM2CzMUNln6b6JoNwZSSeNLUtDng==,iv:BwawgB1NhBjskx/bIdaDsGmHFJ7frs3Z/8e5fgx/6Tw=,tag:5CE9odg6c2j4iYLZFZVjEw==,type:str]
  FILE_STORAGE_DICT: ENC[AES256_GCM,data:Fzwid968xHh+99S5XEN4ha4aLUqEGIMJq4LZvo5zaRjMCMLHZ0Okc9AT9jVW79iUVy4xSqS/VLOoa0eS2OftrBIyvMbUiBzQuzl3YRfWKpnQtwb9vEx27XbwVP/JMFqSIrAUHI5YG0+TF/5ntGHh7yM+rOajZFyvll8PAquaNcw7gQjtUpKM+eLMZTTJVLMwMg71+ejM2raeZCtn0qVoCpSFqHl4p7Zb6he8kH64+GWqOPlED9HQ4/JLqr/waUObSMnEiD/flqlV7ewN4NwQBZtISdkvWlwyGZl0me078E1FB2wdfHxDcDgfY9v0NBSWSSBJxItgFFAUawiy+BG1Ik3XTxehfYCUbqkvHA/f,iv:/hvhI5ZfDliAZa/UWpFrxh4IUFJL/GLryhIS5AWAYyw=,tag:tre+LRKAkT4GMRQ8J7P7wg==,type:str]
sops:
  lastmodified: "2026-04-15T13:48:12Z"
  mac: ENC[AES256_GCM,data:o4e1zXQAIyCrhls1Ly9VzM2I3NYKqxvcqcXHnDJlZ1gVewVgJsf0UXgOjlbdoPpBwWud2TAkdCjgV22i3FbrKSnGeygR5zvFqIxsXeuxM4r+68jP8levS8HY/GcysmRt9Nlb7LgxMW1+iHHJ7BqA5YHhdwpx0MKhklBV/hukOO0=,iv:1ypAfYlmeJaa7etd3o1vqxM1BKe6qxcSmX8nNaC0gWg=,tag:sidZ0V6Lag8aeJ91zFgh/A==,type:str]
  pgp:
    - created_at: "2026-04-15T13:48:12Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAkTVqMBgYcXaTQpB2mgGjJ7X8ghb5CH/UCaRX1z/4TfDn
        f+BONzrteO0f2IywgNtUYU9tOngZZVX1dzQ64akcT73KURHSVZbsVV2Ueg+rydyl
        R0ODL6beaqJUzp+6eKUC3jmTwfLoLMOB6gaOg4AcKs7BxDtJwkr6jTtjPk1fu69b
        RdaWrXHWlPDuySozS+WpWo1vr0U7grMRrTmlLwh03fABkOl+JI42nKOdYgvKXQTh
        QkX0Wth9AtYEou5TLBFGjuM9KdYMvBjxwKvrlnG6QQkkMdoTamR66Mvkb0Q+2YaW
        +LG9Xwi8YWlV+zZkiVy6J7GIks86/O4j62NwYI7+JDY2CO1r8rROJ2JmKH+d9NDr
        R9BIEnhCVqvRMwHUBQiUOw3YC5EHR3PFTjk5Zk33Q5cA3jsV1/zzuizQYo/j5oXH
        lYbDeesUWln8bIl86/gOaAQ2+NcpSF0hbZq9ds0RdcaUta9J1L7VDb1MQDibk/+h
        IOrtVaPuTEhS2O36NlNYXvI5M86M/9dGKHd/UL+4qPa6Azip9ADrMNmUWmaiT8W2
        AtkgvrbvG/SwQsR+7J49gaQXTBbzD0iyBlEGXgB0FybS7eJaC4bWJcdzpydpbuTE
        gql4S7fuaTuThbMARBu6hqDLGDA1cB6J6gtOAF8TWr71YWNXM9BJfNyChA2b4/XS
        XgHRRPSDb5krInUaWp70AaVxSFvUeXYktU1BM3+50BqXZ1fRhdLPLATy27wq4qJf
        xV3OrydBB6JfhgZ6DWyljfJ4zwmtBZJluln7XdKP+csRMZ0SBCHL6YhrLnyLx+k=
        =iU1n
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
