apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - ../../base/immich
  - cronjob.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: immich