apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ./secret.sops.yaml
  - ../../base/immich
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: immich