apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: default
spec:
  values:
    controllers:

      server:
        containers:
          main:
            image:
              tag: v1.137.3
            env:
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: postgres-immich-app
                    key: uri

      machine-learning:
        pod:
          nodeSelector:
            kubernetes.io/hostname: razer
        containers:
          main:
            image:
              tag: v1.137.3

    persistence:
      library:
        existingClaim: immich-library
        advancedMounts:
          server:
            main:
              - path: &mediaLocation /usr/src/app/upload
          machine-learning:
            main:
              - path: *mediaLocation
      cache:
        type: persistentVolumeClaim
        existingClaim: immich-ml-cache
        advancedMounts:
          machine-learning:
            main:
              - path: /cache
                subPath: cache
              - path: /.cache
                subPath: dotCache

    ingress:
      server:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: immich.fdk.codes
            paths:
              - path: /
                service:
                  identifier: server
                  port: http
        tls:
          - hosts:
              - immich.fdk.codes
