apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/cloudnative-pg-operator
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: cnpg
