---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nocodb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      nocodb:
        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
        containers:
          app:
            image:
              repository: docker.io/nocodb/nocodb
              tag: 0.264.9
            env:
              PORT: &port 8080
              NC_JWT_EXPIRES_IN: 48h
              NC_REDIS_URL: redis://nocodb-redis.default.svc.cluster.local:6379
              NC_PUBLIC_URL: "https://nocodb.${SECRET_DOMAIN}"
              NC_DISABLE_TELE: "true"
              # DEBUG: "nc:*,knex:*"
            envFrom:
              - secretRef:
                  name: nocodb-secret
            resources:
              requests:
                cpu: 5m
                memory: 128M
              limits:
                memory: 2G

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.3
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        controller: nocodb
        ports:
          http:
            port: *port

      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: &host "nocodb.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          nocodb:
            app:
              - path: /usr/app/data

      redis:
        existingClaim: nocodb-redis-data
        advancedMounts:
          redis:
            app:
              - path: /data
