# ---
# apiVersion: k8up.io/v1
# kind: PodConfig
# metadata:
#   name: local-backup
#   namespace: default
# spec:
#   template:
#     spec:
#       nodeName: x240
#       nodeSelector:
#         kubernetes.io/hostname: x240
#       containers:
#         - name: backup
#           volumeMounts:
#             - name: backup-volume
#               mountPath: /data/backup
#       volumes:
#         - name: backup-volume
#           hostPath:
#             path: /mnt/backup
---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: paperless-backup
  namespace: default
spec:
  labelSelectors:
    - matchLabels:
        app.kubernetes.io/name: paperless
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  backend:
    repoPasswordSecretRef:
      name: k8up-secret
      key: repo-password
    local:
      mountPath: /data/export
  # template:
  #   metadata:
  #     labels:
  #       app.kubernetes.io/name: paperless
  #     annotations:
  #       k8up.io/backupcommand: sh -c 'pg_dump -U $POSTGRES_USER -h $POSTGRES_HOST $POSTGRES_DB > /data/backup.sql'
---
# apiVersion: k8up.io/v1
# kind: Schedule
# metadata:
#   name: paperless-files
# spec:
#   backend:
#     local:
#       mountPath: /data/backup
#     volumeMounts:
#       - mountPath: /data/backup
#         name: backup-volume
#   podConfigRef:
#     name: local-backup
#   backup:
#     schedule: "*/5 * * * *"
#     failedJobsHistoryLimit: 2
#     successfulJobsHistoryLimit: 2
#     labelSelectors:
#       - matchLabels:
#           backup: paperless-data
#     # optional
#     #promURL: https://prometheus-io-instance:8443
#   check:
#     schedule: "0 1 * * 1"
#     # optional
#     #promURL: https://prometheus-io-instance:8443
#   prune:
#     schedule: "0 1 * * 0"
#     retention:
#       keepLast: 5
#       keepDaily: 14
