apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  # Number of instances in the cluster
  instances: 2
  # External Database connection
  db:
    vendor: postgres
    host: postgres-keycloak-rw
    port: 5432
    database: app
    usernameSecret:
      name: postgres-keycloak-app
      key: username
    passwordSecret:
      name: postgres-keycloak-app
      key: password
  # Bootstrap admin account
  bootstrapAdmin:
    user:
      secret: keycloak-secret
  # Enabling HTTP communications
  # Keycloak behing HTTP Proxy closing TLS connections
  http:
    httpEnabled: true
  hostname:
    # Setting hostname
    hostname: "https://iam.${SECRET_DOMAIN}/"
    strict: true
    # Enabling back channel
    backchannelDynamic: false
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  # Do not create ingress
  # TLS options are not supported. Ingress resource to be created separatedly.
  ingress:
    enabled: false
  # Additional Options
  additionalOptions: []
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: backup-nfs
                mountPath: /mnt/backup
        volumes:
          - name: backup-nfs
            persistentVolumeClaim:
              claimName: backup-nfs-${APP}
