apiVersion: v1
kind: Secret
metadata:
    name: keycloak-secret
    namespace: auth
stringData:
    username: ENC[AES256_GCM,data:ErAvceA=,iv:iVP2N/6P67rGGlf46hDnxmMn5HZ7nYEJzkZq5ZCBB9M=,tag:+tqXskUr8V5bP130KHUr1A==,type:str]
    password: ENC[AES256_GCM,data:GMeHhYzVNMhle0ATbQYcPPqI6GOB2qo1,iv:c7DJHGxMxS/x47azrHds3fcw62s+suYbzS+VVpiYVVY=,tag:YkJ/UxSycvoWcJde5tKygg==,type:str]
sops:
    lastmodified: "2025-07-14T19:36:19Z"
    mac: ENC[AES256_GCM,data:pt317dAeljKGDDaYSsVL5mqwu3O5Kb0eiQZ47bHA+zxpubQcKEMOijhxgkItFurrY4SXScDzYOr6GmJu1ZsPt7ak3QabJfWUE3s+G6lTU/kjoBkbep/c4fQJVEvUgREoAw3wtTMyEyUOyfe/U0Sf55rBjDxVBlM0LZWXOJ1aBtk=,iv:QHNMNvE5dPAYQ6+2BHqoVy5uL8P1ynNa4h3meYuFdg0=,tag:xrjPTfhGtDtBFbPlu+9i8Q==,type:str]
    pgp:
        - created_at: "2025-07-14T19:36:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLARAAsSOb1luofs/sUpHd+KRb9qqqDc8RT2vYZ4mPf/rm1IDU
            C4BVpiFYXcsuQVRbWeJ3knZeUGd+dEsd0nGb7XW3ViUlZmNDOSxkxNXzsRwDXoli
            H6uxfHmwcoyN5m31nh3BMcTJZEMUuUF1hGA6cX0EYhZMdgcEsK7rNo4aBqMnVE8f
            qKvCqEBOofXxs4QXgYu/PTKRc4nu7LuLUFXKZ6XR4WlQt9b/H+6p5LXfR/nf9jyM
            WThLp/eXGlOPgKXBjOOViBehCffgCaRRoQ1vHKWqSQ2cSQPY2FmQFw97OCf6vVgX
            7iC7Njeq2FQLiPSw6l88oVotE5wR2mlBAPrt9oBZYGcWruNiIloba85rS19cMFqd
            Iad2E9I/Pfr25OYtNZL+UAggWX6LBnLMczBNq5PFfnwm8gVFxUF0i/lh5fuRfbgi
            Qros0GAcsw0+pau8DdXkzmfSO68AUDQHPBmjoIoBd0omtDsgXN6lMATIF+4voRnU
            oeyvT/+9ulM5YC/qglieOpX3zS+xBNc/UMMHhjT/5e0MyRLiCpf9EsvCs4Of4rS6
            fBV2v+AOCaCNs6bFM2mKHdAz0RbMDC7o9Tty1l2/BbIz5D41+nQRkNsk94rl9nEF
            +WgARlzIWPVdeGSmSh7DqHfV21vJQHd2gfZGEyGGacVWMQHGp2yowUuix3yciTPS
            XgHz641W6U50tsjFx1pp8x9NkUYLY0veS1JO+wp85OCbbizkG05z7E0vRJRHDJWu
            MitmE/47yUCjQ97mSfcIGNg6DN+Rb0LR2VS5+hf8EdFXFguMQ0x3Nlvd+cFpKwY=
            =xULf
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
