---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app coffee-diary-api
spec:
  chartRef:
    kind: OCIRepository
    name: coffee-diary-api
  interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 185
        runAsGroup: 185
        fsGroup: 185
        fsGroupChangePolicy: OnRootMismatch

    controllers:
      coffee-diary-api:
        containers:
          app:
            image:
              repository: ghcr.io/frederiks/coffee-diary-api
              tag: 0.0.4@sha256:2e1f3c965e3eca1068fc73fc22160963e6c8a3fb12a10cd4eaa1e8c51e99ce1a
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: coffee-diary-api-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/live
                    port: &port 8080
                  initialDelaySeconds: 5
                  periodSeconds: 45
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /q/health/ready
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 45
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      app:
        ports:
          http:
            port: *port

    ingress:
      app:
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://coffee.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS"
          nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization"
        className: internal
        hosts:
          - host: &host "coffee-api.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      tmp:
        type: emptyDir
