apiVersion: v1
kind: Secret
metadata:
  name: coffee-diary-api-secret
stringData:
  QUARKUS_DATASOURCE_JDBC_URL: ENC[AES256_GCM,data:5XatIg1xVnP8MqlvVNcMv66FSY00ggCry7DDrTwUsWgDOFrpey4Gx8iUTDb2OdVov2JHsW/j9T0/9c0KGLPp1rHhcUFyHXxveV7M,iv:frGypkGz9dcTmL1jbSr+cBybAc4SSp88yIm+mC4YhLY=,tag:w9LoJh0nOJWO5ftUorxb/g==,type:str]
  QUARKUS_DATASOURCE_USERNAME: ENC[AES256_GCM,data:pMNxzt8ALKRbViVw,iv:Jl/nwc+PHOLlKzOU4jCTDCdVE/mh8qR3cCVpHG63ko8=,tag:6ZY+TW1bwcNQp9piGdjttw==,type:str]
  QUARKUS_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:Azud5JmrrucatDeiEyfKGEH5i10kNi4SaVh8nRa1zDAMVpQ3LdFRPQiqYEoGRvaR,iv:HFYH9Sy4m2BNF43CwUvINwINlAKN9/kg8hVaPfVES5g=,tag:mLkA+iwLMQKEogtF1ybX2w==,type:str]
sops:
  lastmodified: "2026-04-27T16:22:22Z"
  mac: ENC[AES256_GCM,data:NlRZYYldcLgl8ni2/5MLWdA1j8WuOciwsTVCbGo7SM43X5wJRY0MOYbUBFQ37HVWyINgt3S6GOY5CGmcNqHD9v8dKAJjhtFQYDDBVTqPdyivBNE90lD6m0SmimhAgQzaLOfshHv6OVTbVKPIqlheovcB+EY+XyleTh/BhWVbEkE=,iv:771H3hT7dZAWjtXjkw3A+BSapFNwe0EjPjkN272zT1k=,tag:XVngdkZTKLDOZfhgc4D+yQ==,type:str]
  pgp:
    - created_at: "2026-04-27T16:22:22Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAnpJ3CQdGe79uU2u+H2nP89oxrOJ1eXhMiOpOIZaxU3nA
        u/C7kuVj3oVpMArwLspN2ovxtuLW+sf034WdCHLtVXe1PwMGTf2kAm8T/PjxRSSD
        tX21EYPLNa++1RRAxbVNY2dd/qcLPnkAGulVjdWEJDcBuiylhJXFmnFW0KlWmkol
        PtvOGxuNeL0/2Bxewx2NrWf16TUzfp5A0FznoZJa8ANsU57ZC2XkdlpFwkFGJX7M
        ov8+yLalLi6hdJm+PlYgtHm4ubJ1muOBWewYAZ4WAUtjQtLGQMz50c9aQHF8x5j3
        qPOlKOVGYu/NC8LjohawZx5+/TX2mI2fix+vwGx74rJG6SsZhKlPxnHJ/7HTaYZ1
        CtGwrQhZK1GoyR0IxlCT01Z0W3iDPRMwCpgSRYEfwIepUdBvA75LhXgZDMO4mIqq
        MZV+JCSPaJLFnlpv/++9KEgEXCC5K39DGMBo1jIXvKFCV7HzlZfGQQXxBp0zLWdM
        Req2U7TB6csdR9iIotCN6ZxygFvvRh+viJihx9ahd/EUaKCDnhx2kDvuLexhgMUk
        kJqD30iRMlfKB0SnFBmdzdf8wS1r6KuUFPy6JJ5CQ1x68GEaemIt4scLnPYXiWSo
        nCJv8epVmLfOQWw2qh9/Y1eC3Y0SpRqzqcIJ3NXTMt8UWjd6cFXssQsBc+2wqtfS
        XgFFu5ukYQKaX9wGYsYBXafk41piD2xVcctI5YyCVMb6E1Yj+D8Zc48awOhnDbGe
        7rSWAs4QYg57eDSbejYbVNWUyAhWoHYsm0iF0HjbnShhNiqWr/9F0II6Wk+2qWM=
        =A4P3
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
