---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: affine-db
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/affine/db
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
    - name: cloudnative-pg-operator
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: affine
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/prod/default/affine/app
  prune: true
  wait: true
  dependsOn:
    - name: rook-ceph-cluster
      namespace: flux-system
    - name: affine-db
      namespace: flux-system
