---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-backup-job
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: n8n-backup-job
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: &name n8n-backup-job
subjects:
  - kind: ServiceAccount
    name: *name
roleRef:
  kind: Role
  name: *name
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-backup-job
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(TZ="${TIMEZONE}" date +"%Y-%m-%d_%H-%M-%S")
    FILENAME_ARCHIVE="export-$${TIMESTAMP}.tar.gz"
    PL_POD_NAME=$(kubectl get pod -l app.kubernetes.io/name=n8n -n default -o jsonpath='{.items[0].metadata.name}')

    echo "Creating n8n backup"
    kubectl exec -n default $${PL_POD_NAME} --container app -- bash << EOF
      n8n export:workflow --backup workflows
      tar cfvz $${FILENAME_ARCHIVE} workflows
      mv $${FILENAME_ARCHIVE} /data/nfs/export
    EOF

    echo "finished n8n-ngx backup"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: n8n-backup
spec:
  schedule: "15 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 1800
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccount: n8n-backup-job
          containers:
            - name: backup
              image: bitnami/kubectl:latest
              command: ["sh", "-c", "/scripts/backup.sh"]
              volumeMounts:
                - name: script-volume
                  mountPath: /scripts/backup.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
            - name: script-volume
              configMap:
                name: n8n-backup-job
                items:
                  - key: backup.sh
                    path: backup.sh
                defaultMode: 0555 # read and execute
