apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
stringData:
  N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:OAQN3mgTLgKotyKi1Dxqu0I762+Yg1frKNs4htL7BFWqw2HGJEv3pylcqUnsxM1I7LN+PUducN53QbvDgIXOrg==,iv:7XU4CWaVIwhOj0i7nAdDERKlmk6T6j1DguEkunp/r0I=,tag:G9aMbyQw7vQtQ51JTD7TRg==,type:str]
sops:
  lastmodified: "2025-08-31T12:03:02Z"
  mac: ENC[AES256_GCM,data:XtrchLJ+/mNQ38osSjS/Yat0cFHVGCVHjZptcBjm3r4s34a7bDryimPfEJWJvAVhr9eksB5iW9awOccz0ZpeRCCVDXBvvsXVidjve+84B8Ld9MTwuQ0FnN9wmwH4S7PGIwkfixD/gU7l6IBGpIOQDnAg5m5Y19bu+ftl7klo/go=,iv:xAPTeQ05CQMbb96PhA0+AmFxtCRxsrsn7oc3zJyHQew=,tag:p0Vq/qB6Bxvf92e47O+97w==,type:str]
  pgp:
    - created_at: "2025-08-13T13:54:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//bBDuA3UE13QEqXHqDswsP2NvsAcDVvdRzr24C4dQ836K
        hKK3ZJ1CNNAxiUWEyHv+qnygs5fgFYHnhHRIER3ZWp4Wfr7Ntxbm+IY9B8vjyhHe
        ELKgZHxG7o8sBOAM8eQoXDx59S5tY/cvzsL3lTqWHxsMAx7WKMMZwxujnEjF0sLV
        eDJRn2dS4RhZ2xBhipSea8L8kDVaQkJopRFnaaP30br+My2hJ+okfhj7VZF8h5Wx
        eSo4Zfk30fx4D1LAbVvCEt7bFk++Md301ISZ0k+hHjoc7XZOfw7t8hZJOm5LdeoX
        Zq7hto86Mh51YdpFq4qoKbn/rjx90eBRBvpsbzjrBE8TZ7Jt6rDODgfce/3z/KoJ
        fjHZGlnDNFWQOrukvyhUQF03QyOqyASYmOCIMTRewXoJm2DgDmhtKnQL67ws6Jm/
        fVxMrWd7qr60iy+EVmM7TM+Q2InvHHwzYbKJGlEvt1NSl6WRxVjDrONJpQnnIlh/
        B7JiRvusgiuTPT+Rrfz/1OTO2NLfShcoUivaNSZ/KMYKKaAQuE/iNKsWZPSkjDoc
        lgGk+Z4kc2tTD1bG+qPkFZPRY0vJjnreWf5V88hHIWR45UeXApULizof3I48SpHG
        /uPeXwmRRFYms3Y8fTOobZR+rJWSz4625+jlmdJuv1hGayzRg2IojXP8fO77F1DS
        XAEg0eGn6y7ea0sXAiWBdG1E3vk9WvcTqS1FSRmfA0SrOB2rlHiHeK7CESW8Anf9
        qfaJsifpbDA8vkezd7n56X/dUk8BCRvPYvA/hYJcKbEGHUSJKfawpgvlYEdN
        =+RCU
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
