apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: default
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:fqY7P5+47X5Fvpzmv1xXPBfhAf3oCdtBEiPx+90AoN24jnY4ZvO9M/xRrf/jsrV+2pRzJVFQdAL/W8VJV/HUxw==,iv:cHbspWocFPJ1TkO2pCfO645gV6afx/VGEYVU+8sERiw=,tag:1P5UQdyrYLSxRcR2clz/SA==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:4BZa5Nk=,iv:h01xoOWT3bgn+T/Alk8f9y7gxe3Lo0CzMe4kC+lRX2Q=,tag:5G4BBxIfr9ZaaaMbepT8nA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:ihJuOXMTuUJnxDuk2j13Fp374gUYA3bo,iv:3Rd1GvuojQZvVtPekfwN5ojH+6teKshoVJrCNxNUh18=,tag:57YidfwaN0Ar3casFbRttg==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:nOvSbbDVNBPFEGAjcyaGlVOYeC2AOda/cRV8JR5o+tLDFyijU3ZQFYT8Pj1Mxrikb/xlf6M9uNsdR/eFG9dnDLrDKd7m2P+tR0iQ5DA+hNbeu7KO0AarKhEEGGD4kJDlZiIJtTAF/lPnLf6lRhVTwqtsrEqzyi3En40EyROxSFnf/8sLrjqvjXmggBBecwbLkc4VU3ZHcF+4Y9JyJzep2b5SyE+/sB7RGgJpF/QfOwB+DGReP0K4mdc9Wp6iqTP/GLqIDnvlw+0GFdgFVDyYfOLUVzrORxjefPnb3Iy6sALO2s5nj9f0n5yVIypMQiqJNh+430/4LAhYRixlZl/rjLtKY9uIDXwluUWxXbsMfrhqkB22zZfU8mylqnuB0wRIW3RSvOO29ziri3c=,iv:AmsHuhAwDM652f3mOGZap+tpbFj2MAYczXC5CyOZ8DQ=,tag:dbNuq/uE6t4GnFE7N8XpBg==,type:str]
sops:
    lastmodified: "2025-07-16T10:50:56Z"
    mac: ENC[AES256_GCM,data:xedsaj3/AvVJBz3McqDapbgMzjmRW7IMzUMZFOJGkRrpZRcG+VP8eRuOFPJ2xi7iVMWgEyYpBhRkOW5qpCP+gns5wcXyVOJzx9Es2pGiTceWva/LcDgbfcvGZDrFemM5fLjEwM53nyoe7R28f8sVqjY/hUgNrgt3dXKa4Fx64aM=,iv:j3GOQDBnxoZICnsMgzTrg49cFl148EkQByTGsyfOY9M=,tag:vz+TUKMnadqi4vR7dby73A==,type:str]
    pgp:
        - created_at: "2025-07-16T10:50:56Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/8D1Ju5x2gSgS0X65nyUl/tCQNHax9HXxR1O39xZ4Ipuyn
            uPSxqyjHry2zH4gSoFvgPJjJTR4k/GaeeEA14qzlshWsQskD6ziIPTqyh9RPo7iR
            ZT+Vguup3ShOkyD+K7AMQVdzmaZsZvV+B+izx7cIfDavRo0qbB7v6nMCJCCaL1CW
            YHPplfj9d0b+rVFsuF6YtPr0YBcxxeqewC2z4yX8VMDsvJ7NQcCg+ARfr6VA8x9t
            u+Qk0HcqDr1/3ux6aiHWlvqaXRK9QOZ+5UTb8tOiTXjMJEj7w+wi4GoTuG/p02lP
            iscQCEuz89mzyWehEJn7F8VEB5CCkHlaUxuvklQIpedqGiAmcMHe8QCvZ2wclP/M
            MnxKWZlt7q2NcqG0mE16sPFNq1QXEe8PN8qGIXUS9jcm1CRW3y2vkYlBQCO4lIUH
            CKYuMbQPEj6vtXzUTnRc6IxPJi1NQ5+1jDzFE70RCh5SVFI75T5NLvgK4cphQT+i
            pnAtRC/Aa3Fqhs82ULAAAu095vSCFmJeSWUANvKwEwtwdsOOQ/mVUj0JBamYQipt
            H28JYHz30cdIwRFVVCJRXpSH9BkA0BpkS+yHW87gOUNmt8Bt0rUmfCXiiJ3BnlzT
            WwXy4GJaMCE28McA0aUjEBVfl11ZQpALhkO+36O7HX+qpwdp1pTfB/MLltrmH2zS
            XAER38bTfZ0lQE/lxt0leWtO0LP+8nlUCO14qTm8cvIJNdpkkvQhmAh3XgZn24i2
            daw6rboNtY6pLWnLS6OTgYNH+a/HSJ5roHiB7SaeNAcHjE2OkYS94AE/SMc8
            =omCF
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
