apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
  namespace: default
spec:
  values:
    controllers:
      paperless:
        forceRename: paperless

        containers:
          app:
            env:
              # Configure application
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://paperless.fdk.codes
              # Configure admin user
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
              PAPERLESS_DBHOST:
                valueFrom:
                  secretKeyRef:
                    name: postgres-paperless-app
                    key: host
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: postgres-paperless-app
                    key: user
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: postgres-paperless-app
                    key: password
              PAPERLESS_DBNAME:
                valueFrom:
                  secretKeyRef:
                    name: postgres-paperless-app
                    key: dbname
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_SOCIALACCOUNT_PROVIDERS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: "true"

    ingress:
      main:
        enabled: true
        className: nginx
        hosts:
          - host: paperless.fdk.codes
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
