# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app changedetection
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      *app :
        pod:
          nodeSelector:
            kubernetes.io/arch: amd64
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.50.11"
            env:
              BASE_URL: "https://changedetection.${SECRET_DOMAIN}"
              DISABLE_VERSION_CHECK: "true"
              PORT: &port 5000
              USE_X_SETTINGS: 1
              TZ: ${TIMEZONE}
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
          browser:
            image:
              repository: ghcr.io/browserless/chromium
              tag: v2.34.1
            env:
              CONCURRENT: "10"
              DATA_DIR: /profile
              DOWNLOAD_DIR: /downloads
              TIMEOUT: "60000"
              SCREEN_WIDTH: "1920"
              SCREEN_HEIGHT: "1024"
              SCREEN_DEPTH: "16"
              ENABLE_DEBUGGER: "false"
              PREBOOT_CHROME: "true"
              CHROME_REFRESH_TIME: "600000"
              DEFAULT_BLOCK_ADS: "true"
              DEFAULT_STEALTH: "true"
            securityContext:
              allowPrivilegeEscalation: false

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    ingress:
      app:
        className: internal
        hosts:
          - host: &host changedetection.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      datastore:
        existingClaim: *app
        advancedMounts:
          changedetection:
            changedetection:
              - path: /datastore
                subPath: changedetection
            browser:
              - path: /downloads
                subPath: downloads
              - path: /profile
                subPath: profile
