apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: "6.8.0"
  values:
    ingress:
      hosts:
        - host: podinfo.fdk.codes
          paths:
            - path: /
              pathType: ImplementationSpecific