apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 12h
  values:
    controller:
      service:
        type: LoadBalancer
      # logLevel: debug
      # nginxDebug: true
      extraArgs:
        default-ssl-certificate: "cert-manager/${SECRET_DOMAIN/./-}-prod-tls"
      config:
        use-forwarded-headers: true
        proxy-buffer-size: "128k"
        proxy-busy-buffers-size: "256k"
        # error-log-level: "debug"
        # allow-snippet-annotations: true
        # annotations-risk-level: Critical
        # log-format-upstream: '{"host:": "$http_host", "x-forwarded-proto": "$http_x_forwarded_proto", "X-Forwarded-Port": "$http_x_forwarded_port", "x-forwarded-host": "$http_x_forwarded_host", "x_forwarded_for": "$proxy_add_x_forwarded_for", "status": $status, "vhost": "$host", "method": "$request_method", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent" }'
    admissionWebhooks:
      enabled: false
