apiVersion: v1
kind: Secret
metadata:
  name: vpncheck-secret
stringData:
  SERVER_CITIES: ENC[AES256_GCM,data:fm+a+dMOYQMM,iv:DcrAJUuOkddDdNHKrSyf77tUjAeuafYFQMh9vxYS3SI=,tag:PHt85q9c1JKJpM6AnSb6ww==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:hx2t6l6TdMkBusU=,iv:g1a25XtdCfAgO2xaxLHGHqyvDe1WPxw0sefCIsNUJho=,tag:SyQixgfOE+pfOQpm75Iljg==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:5y9OXizpXQ==,iv:c9VB6VadDD4Q7VIuOz6Gc/g3nLFp/tpIeI64myrzSEQ=,tag:wqUmKOLiiZNv1uUrlZig+w==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:2lvT3YzuZYrp,iv:IVkFYuT40MOBGFsQd9WM5DSMr47wVIY5FB0ita6RxpE=,tag:APeDmd7YEfTLBqkLhKqOjg==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Hq//zHVVonNzUnCQyJyCnE6oJ6mMRmvnYQKiWAAEp6mqrnbwtK8KxMlV4kM7eNQw,iv:I3hwiAsKhn2sYV/j8qYYZtZ4xDXw4LIV5dhvUt3gYgQ=,tag:eAMq+/OlwnUVAP7UxvC+yQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:FTLdYUolB/c9jZHImNGUL2CLkuCruz6MeGdLP8g23J6c307eMktzdsXGsoc=,iv:xZ26DweJM4gjY8+BVb1qUrav0u2W+oVMH1OrOekDknA=,tag:8v3IOI1VSXdYYoznq7uC/Q==,type:str]
sops:
  lastmodified: "2026-02-24T16:59:37Z"
  mac: ENC[AES256_GCM,data:wtGzWo1ywzbokwLOgJ7c6WPgWu+Nn5eoQpi3Ky4M70kbqBN41Uf//weiBjY76nlj9HSWVRfEkFCfA5VIYV5+alyl4vFPyOUhm7mIeYf9cIyN92NoqnezBBdXE9X4znEX4A1aPw8/tTuhyY0ReVNsHfuR/nah+7tpQ1HqmjRhElY=,iv:WFMoz+Rawmc3ZDHuSctv9vcQGoie8uYtmYAn3Ns3LyM=,tag:UwWOGaD4LWkz+tsl7jGQpA==,type:str]
  pgp:
    - created_at: "2026-02-24T16:59:37Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//aJNLSNyMow9GFZHQmLswR8ZHgcfqHs8XF9i39Kc2VSwG
        7T7JQk0NPQDAqNYYhXyGm3hOjUIbHUE6w9wDiHmAGKcPPffPCav8ExvU4u4WaiwQ
        DGTrlKZakL4b6lV8IYTT65EfyIq6jUwEjpNtpIf05OfeM36xdi0tfxNHqqLqSZ9L
        NyTgQDQGq51uCFhfB/dk2uX4O77nHBgUnj+6CzxvlRehl5WtdQLdSH5UoXI4I1FL
        IrTriE6Nnj6BVHscYila8Ya1Z11lCFIEUqoYPAsoZfaecDlkYUnhyQddVd5Vwyyj
        FqESFt77Dic2tFdrV3ehpchOkUwpqO9B0uBil086CO59OCJP5nn5ZkInv6ZYMI+n
        8KHICMwFxt1sjt0qXJLjWvV57TEvOhftu/hDuAtdz0ss22SC/4x9NDF/hptbdVHj
        ol0wYwaQ6SLm7JYAmmIhBbtOzwNGN4t4jFWUrsiC6vIGk3nZ/urnwoTnao4Z6wde
        tGJVsG8nNIqTznvRDhPWzTavz8Xn+BMKvtBU+MUik+LBqDqAtC97z5KGMGYR/hAZ
        CJYH/Ybg4QqPSJ93LUfjY51YkdaDBvSml7UqjF7MAwv+zcGIipjrj0G8AmyiYw/5
        Wob15M9AnrowvQ6kHllgOKpH8yKyrFyOjqSJCSR0xOutk616tmtyNLYCH3EMR9TS
        XgG8lkDdWYg13/A9rbTtiYgR/1JrrPej6DPzFkD5OotNFqK7MB1niRMzqBKJeILd
        21JBINprKceZ7cIYrAVvRpX/ykKRfsZ1N43n3MeDYGDCKWB17oj8rdPBXRZRVRs=
        =+NAy
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
