apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-credentials
    namespace: networking
stringData:
    credentials.json: ENC[AES256_GCM,data:RJoPA2Px1qDSoMg8QywwIN+EeTXmQA33hFNVOP7ToSizPB15MVh9535ftMT0tCd0kqAy11k5zX+KkZDXe1wGRVxOsS4g0suk1NPxNfnMoB3d6HmUkMtI1svS3lbYQ+Ul7CRkdhEq8cYFDz2tw741k5MbVzhvl5if3q7DaXTH2O56DR+sIXqJsqRBucDNk0rCbFrA9/zNRCHj0QbJB0eEnEUc12bZC2mVM3jRZAQKMnFwvw+zgVcYKBz7F37/rADhjxk2WP5dUrzdcJgF0PJXZUuUW/hwkIVKRQPqrVsteryl5xw5N5MZZ+AEjYxboGXHFYM1PztD5lY0IHuTAoFqgkTdSqWuWwq53QG2t6HrosiD5VlfuyoCMkAHaTOCW9X8Y2dg9t7ty19NofsGXUCiF6bGjwyg3AZrgx4=,iv:SDRufNVePOfmYrD5D89jALQOY4iTq9OLxAtk+yPrQZg=,tag:aEC6qYyI7mSj3yNQbyfy7g==,type:str]
sops:
    lastmodified: "2025-05-04T17:15:45Z"
    mac: ENC[AES256_GCM,data:hjT4jsR0HO7LNR0Dh2abl+yuC8hXoDFkETycPdPwgnvYsGa3Tq3kkqI8f0b1g/7iE9R3Ki21ylpiieuIA4IoFxVm2KXExjRllKmoHdeko04nnJtTpukqAzO44AjLTFBt3tQbmuSEbSMV2+kTipecZNEbghpN18sEfJHZwsHhIdE=,iv:4lIfUsKUDjMMb3ZgnU5DTiDalPLlJ8s5aYleSY74f9E=,tag:tL/4NFVgQT5awmQ71wG6QQ==,type:str]
    pgp:
        - created_at: "2025-05-04T17:03:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/+M8HKW5Xi7slQQPl18HANrGhuL1B2yP6trFRVsmILA53u
            qvumWYHNVhRUWxY4TF3SAPbCYQp0oSqnct8r3hBZ5kHHi+BsoK+BSRD5D9VZDeqT
            ScH6sl0G6QUDKgLmdMCxAssu4keFT2Q2WQdBNUs8QKq28KXZn/vxvHF6XAGeRX3e
            odn3jQxKIfn6Z7aUy4J7ykWS/k7GKFFgAS3fz2TMGvZmBUgFmq6qTjZYRR05uAoc
            tTmCRLXvcuTkDWdj6dFEdMKYC2rx3EfmmeaXS7Hh+2pI4cJtgQ0OR14LRGKCX7YU
            3FSx8I3iAKKueEi3vA3BcrYcJ1PMDY8QAm8wcAu+TcWlqczJ6Wf2AfF2KXxnq9lZ
            nXuqZUK0trPD88eQfq5tqhSI1xJqYK9ey6xY6aFT/8SfpJcgnzY4PYi+p7R5arnr
            L8cW9XDVYVarmD3O1mKfDTlWfkaKpbhkpQyKJkn7MHo1EeBfk8dQKPZcU3kC9BQd
            8VSwvQ3vF7lqH9nc4NSeGSwwqA8kAFGbklK7WsXL/ur2QAENKyB2Ip3bAyroDOTS
            qrTzHmE9/KkQuOPHS5c19V3aEVX6MzMIM58ZqIhNyMEyAcqVVKmGQgwVyiXUaK1E
            4j9YKV/1M7VUj/z5fT8av5gB42o1K//9L2TsWpY33Rov68lWDN1I9CxPjUmM9bjS
            XgGQLRZHB89cQvsI5tcAUhAeN8d2ccHmpMo6sC9ItlG1fphljmajJIYU9J3PnXWk
            Ln0TqIKvpNOxIiA9r4e7qASNzAEotpTNVKY3LNg22oKNRAg43N1Y4EeZFY0qXbQ=
            =Eeod
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
