apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  values:
    cloudflare:
      tunnelName: homelab_ingress
      secretName: cloudflared-credentials
      ingress:
        - hostname: "*.fdk.codes"
          service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local