apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
spec:
  values:
    cloudflare:
      tunnelName: homelab_ingress_01
      secretName: cloudflared-credentials
      ingress:
        - service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local