apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ../../base/k8up
  - ./schedules
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: k8up
