apiVersion: v1
kind: Secret
metadata:
    name: k8up-secret
    namespace: default
stringData:
    repo-password: ENC[AES256_GCM,data:tNDAhrfzLjLzzOcWp7HNgehH62KAe4jw,iv:EimfNkqZSnMEV4p08Nbf7fEIAqEl/5rkhSHOY9llHcs=,tag:7LnIHxUzIgy7aQuuvUT3uA==,type:str]
sops:
    lastmodified: "2025-07-19T20:01:50Z"
    mac: ENC[AES256_GCM,data:0WvTwsooucW9UetjrxfJKNb+ynJwa0WqkE7kidaEeAEATIbkglpZRXsHnJ0T5NtmT38dGl1+baKIzyLhAu1jUKS9rKNv9ImWN40obsoVxvd9bPQlmMvtDFkqdc5IaoKrixkbQSP0vKBeKOMGzC0Y+aE65LOjY+ZJITP+0V1pRbc=,iv:/MlfeRxrO4Wv8fZcJDRazJfprGx5S4QzGrSffohqQeU=,tag:phwOgc5jJD24JUiY+T8H7A==,type:str]
    pgp:
        - created_at: "2025-07-19T20:01:50Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ//RTvy/X+s80tXQA+m/G33ZeTaOlaC76OFCBLLvVod1bMt
            4j8Lp3LmKhA2se6ure9zFRpyWF3rpqtcy4SNEuS9vAcUTGII2OR/6KxzbWVdvCmo
            1jzdsOn/0Rz5kyRYq0ZDuFv/McOirReGxZPtb8gUGXwf528+5vQ4yJH6bUqtv2lx
            1lB11Gyofon9J2Cgzy/VSSwvsMOOeJ93VcU2tKVtPNPGWIZAcFpwlyL8cSp6hr8H
            DdEQZpE8UrBgCogj6MS//gOPGPpC2MDhto2QA71OyM4rLYtai3ghXv3vbi+Wyt3S
            sBx7/t0be/WbgDahWtED6dcd4jMugXuZG6mbkHutaRI/Nss68QR3XhOl4f2nTr+m
            dOXULqml9oCj7KSMuvvg07OhoeVGyKOjIvPhVpOz3fjuUgB9+oTrd757dQvPQ3pQ
            lMjz8eUf3p5tAqc+YxjzwZ0h3rUaLkfjFSQKW6KErBCxnbPutRdbkRmQS73BBebq
            iGmRux6xGGs1OuSrp4TeciO6+LQkYPr9kZW21cSKdtV+0JzhdNd7m2igSOCtmnx6
            g2qfI18K547G8FRnWS8/kY8h3TNGRaDhh0SNEddIHcpYYVL5WBKVJytzEAYiXMbJ
            Y127bniOL+RsJdF60tXb3lybSVlqNVg5HbwQ6z5Q1ydXfd6RAjET4EShnMv47fjS
            XAGl/Xk2wy0hzsPPmLsUcCQL825HD0QbrJsWvM5YIdENnzXjd/W+wkmUtRfpKht6
            p0SUCkGsIwg8UKta5scQlIsqAO2QWU+Bdl7tWsZx3fM3NIwawfpxVVcbQsIS
            =X+65
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
