apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
  - https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.3.1/kubernetes/kubernetes.yml

patches:
  - target:
      kind: ServiceAccount
      name: keycloak-operator
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: keycloak-operator
        namespace: keycloak
  - target:
      kind: Role
      name: keycloak-operator-role
    patch: |-
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: keycloak-operator-role
        namespace: keycloak
