apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  # Number of instances in the cluster
  instances: 2
  # External Database connection
  db:
    vendor: postgres
    host: postgres-keycloak-rw
    port: 5432
    database: app
    usernameSecret:
      name: postgres-keycloak-app
      key: username
    passwordSecret:
      name: postgres-keycloak-app
      key: password
  # Bootstrap admin account
  bootstrapAdmin:
    user:
      secret: keycloak-secret
  # Enabling HTTP communications
  # Keycloak behing HTTP Proxy closing TLS connections
  http:
    httpEnabled: true
  hostname:
    # Setting hostname
    hostname: https://iam.fdk.codes
    strict: true
    # Enabling back channel
    backchannelDynamic: true
  proxy:
    headers: xforwarded # double check your reverse proxy sets and overwrites the X-Forwarded-* headers
  # Do not create ingress
  # TLS options are not supported. Ingress resource to be created separatedly.
  ingress:
    enabled: true
    className: nginx
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: User Management
      gethomepage.dev/group: Infrastructure
      gethomepage.dev/href: https://iam.fdk.codes/admin/fdk.codes/console/
      gethomepage.dev/icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/webp/keycloak.webp
      gethomepage.dev/name: IAM
      gethomepage.dev/pod-selector: app=keycloak
  # Additional Options  
  additionalOptions: []