apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: ${APP}-bucket
spec:
  bucketName: ${APP}
  storageClassName: rook-ceph-bucket
  additionalConfig:
    bucketPolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::${APP}/*"
          }
        ]
      }
