apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: networking
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: ">=0.1.0"
      sourceRef:
        kind: HelmRepository
        name: cloudflare