apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
stringData:
  #ENC[AES256_GCM,data:RTBuRQ==,iv:2kl/GG56Pfdc5dnrUYuT/MoLss3Oso55JE9l1JogTEU=,tag:mDGPpHyhoqRVO00mKAUaTA==,type:comment]
  #ENC[AES256_GCM,data:ubu1Y57z/iWCSGdbgCfTaQ1mVXpTB83g7pLtlMqdukxu,iv:g0UFJQ+xtow8FuTuagoR/JsvPTgPIS00SQJxfO1ciTU=,tag:X7shemHm2d+BXZRpw6VkJg==,type:comment]
  #ENC[AES256_GCM,data:OzlqFaM=,iv:X8eK9q+JR5OJx7Yxmq3O5ZzZe58TBAXx1EAr4iAEJ1o=,tag:7po5YWiPBjXu6JL+CJXeWQ==,type:comment]
  TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENTID: ENC[AES256_GCM,data:xpUGgGRPn4c=,iv:QHP/Nvyl16Pq9Elm5frMk/QnV5hPijokaiAgg8Is4FM=,tag:4ZuP2D4tzrN5veKP/KstNA==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENTSECRET: ENC[AES256_GCM,data:IyK3aTDCtazsjYs3wkQnw/xJalx9Xj2GH2pCRR7HGU0=,iv:9wVhhqWd8GggxHt1dbVqss1TilCWwqAEv2fIjRejqro=,tag:/3AMzWV+0uoGcF2hNwZ+OA==,type:str]
sops:
  lastmodified: "2026-03-03T11:33:47Z"
  mac: ENC[AES256_GCM,data:9WfsMIdbjsZSTWgnbNSR2ulpFlhiW3A8jfFI13vOBIwoEjZAeg+atPN1goZeVoDr7YmkYaKTeh5UWOGlTJgQ0nDY7FY3ugBUXnwZ3TBvNA+K3toI/eQYeGIwtJDgkhFn+SLAYreB27CHoE2QiCo7tbn5EujI/RToKL4cooo1fjA=,iv:p9X5VKCW5ogXoaSmoqSScCw9v+z3JBBl+0LDBXhhEuM=,tag:6eqogyDsIRIyxxz0ghgSPA==,type:str]
  pgp:
    - created_at: "2026-03-03T11:33:47Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLARAAlJ8Bi0zo6z3EcMqrHddE2WObzksvcIr3/nvPVVrhYFWh
        8ndM3QGeVTNc2qNSpmctsutVSwAPyo/nk8I+/ck0e5Q5qizpHv4UWF8HJPcV+UCT
        Vdgt2d4nb8/uoxV9KYl17S4hbGcS2+ryqQjQQfxAjFp2R4nFRLx9qFv8KegVvJgx
        lA0vsDfL6rNKlT2MycB4PlALJbI/0muWCm2vPW0XyM8nUF3DE6404lVbmjGWWrLs
        VnCPsDJR87cJvcYrelDUY5+LpQtJLszv56mnZM1vjJ4uJgyALCgAEXkmYBXmzCQq
        s5zWFUHxVNUJRFqQipJUdL7MDXUZvPtz31InwDgJGiJX73lYJ5vWK3jhbFDpeYZa
        U5IhACXePyKuFNIKVeiha958B2V5JJNW2QXAC39MJST3Z6LNf/F1PUNS+QPF7Ds9
        VSbc+yJV7HbbRpNCrwdRadKCoU1UaMvpNkUyYWt84J4Z3HN9/Pen3p//i9QInLM0
        se0IcqyN9PKPSvGPKkOcNEjWgw4U+KDFfbBvswAGXT2GweV3+hmtdv6n31Yrp7TK
        PdZlWIWkwLhG/mZEa7Roy+V80bguv16yBlte/B+pCe7Hm649MEXzhri9Giv1y3L3
        HQGbQ998qWKXXWckKZosYHhwg7T+fIv1g8H5L12nE13ayVxfRdkorUFenwM0rDvS
        XAGbdjvgRfMO2OlZ2VahR8caRGHeNHTKsEm6Hm4p+T1J6to369XXyvgfiHIT+JUe
        WI5HTzLBEnh/Cc8khsSRwjaiEMKQ7K0YUdHuNCVNF0U3ZnMzpIXghpbTQQ40
        =KLLt
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
