apiVersion: v1
kind: Secret
metadata:
  name: tinyauth-secret
stringData:
  #ENC[AES256_GCM,data:mnQNtg==,iv:f8eOsjrt8ImeQarBYI0xbQUAoryjhqlxIXpnXB+Wek0=,tag:/ndaiUkJT4i19oK84J2iOg==,type:comment]
  #ENC[AES256_GCM,data:7NeeRXJA1FtiGcu+GhUgP6LP+XW/8wvMm9txuBPD0Kmi,iv:WNgEHBrgz/yoVuyPYCSGuW8rP5yponES4sPH4tO25wE=,tag:FXqMPNZ2nHdXJS0WyYbbPg==,type:comment]
  #ENC[AES256_GCM,data:FTkfmjg=,iv:rcR0zrD4VaWRKNlALGtsEcypppfC+PFPIZ9Dub74Xks=,tag:4SbQX3QPj4xH8U9y16oVLA==,type:comment]
  TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:B/D3hiCwbc8=,iv:M0O2WoMit8SLL1yaHQabJQplzuROREnnsG2npY5eF+E=,tag:j53FZLT5XHioXCbsipWIfA==,type:str]
  TINYAUTH_OAUTH_PROVIDERS_KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:Y2YHvMvxV3uO2//v13gBhNojOS5ULyuC9K+YhObgD50=,iv:3tK/7gEnDzkuaa3RSWAjGKR+s/N17JE/CchsMk9Ek2g=,tag:IB24L12qlHNHaQ/2R+VmFw==,type:str]
sops:
  lastmodified: "2026-03-03T11:30:21Z"
  mac: ENC[AES256_GCM,data:9LPers/cpZX5QnCI7YHAfGSqxdBfRKsMJn6ioHNayQOlUiEPXUPspL6Csn8a+Ryudctndl5/XUDQumYtD1rnviVStKaA7dQPHsC0pfl/ziGGUkEt4PmG39/p2NLy3KLlpJv1tUELDzuQWTfC14qMgJM3pMKX/4KO0GbeIFJYVT0=,iv:+0pbkVhzg7bpY/qTm/buiT6alVNlzXdxFOhne+yO/k8=,tag:4uHMGtKpU7WVxKEg4ZhdRA==,type:str]
  pgp:
    - created_at: "2026-03-03T11:30:21Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/+L8sIReD2yS8xIwyM7mNq7wh/irv0X7VHA0urfoDdqZvW
        R9LoHhBWwqHwoIyfOF4cqL75qeQ73RszsKDkFkBTkFXuglGhuWcn51wxRzCWK65u
        kYcsi4ieT6kGllKjfuopYSjdbdZPOZXllAoo01VXTXQfyMYa7ENo4w/Hh0/0rN6L
        jIUyuFtlmMGuTArzpZDcVtgul25zcWAN0T4+r2NUvMdHTWe1uEAt5IdLg/zrMX9N
        fZLnmLZv1fIq5jQ61xKxq/fMciCUpA5IE6LaKkP0HGiVLpThCFCn7/zcxodeE5X5
        hm5+xJm9shtqRnaT+L5i2ajOYSoEwLN67rj4DAAUpdWSgfOxFaodt3uIoZdYfb7k
        NTCuiiWTcq46rTEPXv9jbLlLlQhk2zRgJZfnIZxioSlYf4nsDVQErxSxTXMuF1gM
        DjD/4J9QflR+DqPmk5Kiz1a20olYD1Gncoik7hrFnFmsHLAw4g8oayEID23CRNuN
        83FTO0SJ7or3FRw16wb6OIvN8nNP6vlhrPaOiZZiN5MbDKBDgb3OU3pyUOZrj5+4
        CT1/pkqPB0odkvI51W9C4kznosLVt71b9gi3u5sDabsBeKKczPpt9ud9MxcAj2Xx
        iVPS8DrxDIG9Xq/tZAraNigqtb6L5CCCF4qdWgPjcqkDfHbrCWYPSUfF3o/5qw7S
        XgEvpSiHub7hbF/5TXDwlUyQN1pdln2jt7N7me+gBWtJKI6mEERN7VAVza0O6//Q
        ily9/2ZL1PnxqCuhGemUFm9zQvdvuRXtOuFVIw/5hjjFgZcNtZhTDCt4sXjv7hc=
        =k044
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
