---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app memos
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      memos:
        containers:
          app:
            image:
              repository: ghcr.io/usememos/memos
              tag: 0.25.0
            env:
              TZ: ${TIMEZONE}
              MEMOS_PORT: "5230" # https://github.com/usememos/memos/issues/1782
              MEMOS_DRIVER: postgres
              MEMOS_DSN:
                valueFrom:
                  secretKeyRef:
                    name: postgres-memos-app
                    key: uri
            resources:
              requests:
                cpu: 25m
                memory: 105M
              limits:
                memory: 105M
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

    service:
      app:
        controller: *app
        ports:
          http:
            port: 5230

    ingress:
      app:
        className: external
        hosts:
          - host: &host "memos.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /var/opt/memos
