apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-ceph-block
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-backup-nfs
spec:
  storageClassName: immich-backup-nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/nfs/backup/apps/immich
    server: 192.168.0.104
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-backup-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: immich-backup-nfs
  resources:
    requests:
      storage: 100Gi
