---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      immich:
        forceRename: *app

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.136.0
            env:
              # Configure application
              TZ: "Europe/Berlin"
              REDIS_HOSTNAME: immich-redis.default.svc.cluster.local
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4Gi

      redis:
        containers:
          redis:
            image:
              repository: ghcr.io/valkey-io/valkey
              tag: 8.1.3
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        forceRename: *app
        primary: true
        controller: *app
        ports:
          http:
            port: 2283
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    persistence:
      library:
        existingClaim: immich-library
        advancedMounts:
          immich:
            app:
              - path: /usr/src/app/upload
