apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:GTIQZgSh00+FQOi6nlbX7GF2LIKybdpe1pAdaxn4oGU=,iv:VUFDfgIAvBCj3Lc7Sk7Vj5EOBTedSFRIXVxQN1yHjYY=,tag:SKoOTep7JlMGbvA9zprDBQ==,type:str]
sops:
  lastmodified: "2026-02-26T14:24:32Z"
  mac: ENC[AES256_GCM,data:g6dVWQHw7ATsfG6BeaohVjibYdkLj3YIT+7DdwGx3rWOORfwvVjkNoinX0dHYIdLGE72j3MnLsflrnbnw1Djlr/OlujaIsZt3b1xQKqMpweZJp3m43zo2AS4959aN4Mh6lk52JyzPsTAVvikMhiBqRlFswfWLAxl15GegDLdsVY=,iv:MJOYZlcQGORVNrhWIjzr8MpsfUfbgmrhK68RBKGjWns=,tag:lsTbs5VCAcpX45QQd+cmKA==,type:str]
  pgp:
    - created_at: "2026-02-26T14:24:32Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//Y1kMePaaHh3LWIvf92Apf6OR11F4hzbN4YKgi9fSyd9e
        BiPZlJp1+rgXnldmMMtfHfmZQ1UEdghbDg4IwGu/xv0IkvVt39CvPfiRkrIgs6Xm
        GXz0RT2NOVJGaJyvlLxRjq7ThZ5Z4VHb5Q3P59zmLR4LMYAIAmIcIdukcRvBrB5x
        cAAt8QnE9wybdFV6EZnLe31NFvL+4jieoHAQmPGCtdFI4tQUWL30riVXCXp4TrNu
        SpuTZcJPD+ouOXd3uEEpB6jp/lswIansGdmiD9anOgzdt1nU8EIgIR0bB3u4CwRC
        qiApHyaHIJiSnWUsauJcU6FDJLo1rWPQsouI14zJa4oox4heh/+z1/k2+czXvdnp
        Byg6eVX0NufVdN+vrMYW7SejYiTsCrRW4wdpDIYw+HJHybbFUZA151JszFLEqlQ/
        kLqIELmO4MYU3BG0fFEvwtYbrPjhp8Nx/GQKTnBAwSvgwRi159JtbMCpa/I+9+21
        syMjZGviKkHxb1ByipMMY+tOeM0+IqcOne1LF6dOJVjx+2FqnV3XTEDsnfEBen8x
        Ws5O2LbSj5f/XtMtzEBOWns/crTf7ZGy4FgxKrb6J6h3tMEu2uSpft+L/o0Xanrs
        ZUjiCREtLZX6ZZ5JnnUjb1jtLsKdh7tcwH2x6+bEvZf/Y/eUJKXN8L6QtaQ476nS
        XAGkP36GDm6cajUNN9aq4wGcK2JCcDj60X0YvTkJ8ItM0TVecDVlWv3T/z7buJ4z
        4b79V+ULhjbCDos8ynShW3AtSOP4l8kK0TFTTUzY37jJsSWIgDpFw7h2gCCB
        =0ac2
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
