---
# yaml-language-server: $schema=https://kubernetes-schemas.dmfrey.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery

spec:
  interval: 1h

  chartRef:
    kind: OCIRepository
    name: node-feature-discovery

  maxHistory: 2

  install:
    crds: CreateReplace
    remediation:
      retries: -1

  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    master:
      replicaCount: 1

    worker:
      config:
        core:
          sources:
            - pci
            - system
            - usb

    prometheus:
      enable: true
      scrapeInterval: 60s
