---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-immich
  namespace: default
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: rook-ceph-block
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 2Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
    nodeSelector:
      kubernetes.io/arch: amd64
  bootstrap:
    initdb:
      dataChecksums: true
      postInitApplicationSQL:
        - ALTER USER app WITH SUPERUSER;
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
  superuserSecret:
    name: postgres-immich-superuser
  enableSuperuserAccess: true
  postgresql:
    shared_preload_libraries:
      - vchord.so
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      timezone: "${TIMEZONE}"

  monitoring:
    enablePodMonitor: true
