---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-paperless
  namespace: cnpg-system
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: rook-ceph-block
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true

  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      timezone: "Europe/Berlin"

  monitoring:
    enablePodMonitor: true