apiVersion: v1
kind: Secret
metadata:
    name: postgres-paperless-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:vviIeOPU2Hg=,iv:lC2yg1/IZhLvo2Yttp9SMjjTU/eza1J2nZ5kg+dVmlA=,tag:GpFwjOSLGqz+k68L/rvxMg==,type:str]
    password: ENC[AES256_GCM,data:IxmKUqN/QcIfBiW8f6f2TYZKmHyC58tK,iv:qv7n979lZ7cXzsE9XeS9qYJPoo/Li2nRzrYbCGA1Y5M=,tag:s17J1V1znb8l8ghrhwVlJA==,type:str]
sops:
    lastmodified: "2025-07-14T12:38:32Z"
    mac: ENC[AES256_GCM,data:JQx4/POeJDcghp+hgVZjndqrc2KA2mhvKWGKqp67S5Anbfm7rtPG9XbNdDryVBGcXplSFf7BrsxBpi68saA0LMeBbqJUnYaUkleEfZWAGa7/fWqUJH9tr0/hx7MnDVK/NF2QAFsJ5cJNzedm6B02nge3vBomxcx8LWwua1etbX0=,iv:4YRqx41Usro0fazHcGdTW+TUwmQCSKQ8WRL2w8pI8TM=,tag:lDodtjNN0FD5jdkGLwMRgg==,type:str]
    pgp:
        - created_at: "2025-07-14T12:38:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/+Pxq8OhLfIIZI/OitICI3MFOC9NYTYXJ3p8kJorlLk4aT
            W6FWZnlVtWOvgl8qo+W/L11oYdQ0ffKExlAV+3MQN7tbqZ/G4vZLC41aFxV8gDQC
            HAps6U7WYS90VVEfIMkYGXqn/tAMk5OZSPnK9tOuPTbsbs0uaiMUCsmmn4P666TK
            JiFGiSUGPlj9zDgMP9qYP3ZiBUtvNA6/htFfrGQjW0VglvxzSO/3u0m2lexMuRSa
            4aioedYdApKTXvtEtDTaUdIyIm7pjmNnXHu+Enr668U265no2DvpDpNZAXL+0BmW
            VdeyUvW/dgM1sEXdAIHP3grODTb3a+FgEQJaMhnB/nR13LqlHvv2WpkxYDHbwAXZ
            1rFFmit0WMjQ2lv2nd2xGbv68tm7jb+eCAQVDRYQKZV+5e5LxRh1rXfdN5Zrkk7t
            Sn6CIjNILLRKicviW8uYw/V4LiD/O1sx04qtc9F28UfXxh7S7ylppQZOeSkdHnU6
            ynbBbMIBLYVPQZO1sEcgInv9Lbyor1X9iz84NG4FyMyaYjh+0faPiEi9wjICvKgA
            70AnElfTWVGELriRGG8hyGxp/rTaRA2C6LYZn2oC1Slgqgcj9J/lCKotiThV1jQ6
            L7stNjQehXe65tBjCVtUDo1ElrSMmp5Gk/3xsQ/5UtHhxS843XFGJVd98p4JAzXS
            XgHlyO0ZByeB1rufmDP+Zq6AIckqyX7bT3BBytAwvnmOXoykcccGg30zUcRC6v+6
            dxUmBuznn6jt5fgZ7KhZrkbs6dPqn0gm2nK6k85m0bZXA3bjadbHj3Rja2pkCLw=
            =1qhW
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
