apiVersion: v1
kind: Secret
metadata:
    name: postgres-paperless-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:qiwOET5b5z4=,iv:BFxrQkDdyGGzjnmN6rSQqc0R01bbN6o5aFdjP/cBHkk=,tag:vKKZIyt95ubtIzJrow9jiw==,type:str]
    password: ENC[AES256_GCM,data:12L41U8uQTp2EgXHG2c9oXdYQSrL2o5p,iv:LEAkhiGtdt9/3iJKz8nqL2MGU2AtJfTi7AOXXtBHInQ=,tag:XF968wsdH20PgUFkYLdw5Q==,type:str]
sops:
    lastmodified: "2025-07-14T19:27:55Z"
    mac: ENC[AES256_GCM,data:5zKl9M0dXki+N8b+ALzI2dRt7FZKxR/kZo0O71C3J2nEmGf1DGWZeTSPS1n4s0MHM+HIuv6gCi2lQ9tBtbU8mXfPqOeuy0a8Qq9+D5y06SKENbGOd6auOPyeF0QeTJk+gyRsDfTblVO5fCjrhQ6MdmOV+urAj5CVBAo/5uRxRLA=,iv:r9aByqVLpnkpCifRNu7M8Sh9D98XD+PTA8gNuNChCRw=,tag:uqIvIYJo2DD3XM3OL62GgQ==,type:str]
    pgp:
        - created_at: "2025-07-14T19:27:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/6Au0JZMbpB6BYDBlLoRlgBOImfbuDiVUhmYP7OQeZZDPg
            h3kRjtFwvVO8z6lxbpAhAMVkz2IHTFsypovE4dY2E7uL15qo59hhOehT6m9WKwG5
            rEVMNf8C59QwddZ7OhqbofwbswZCBNXodZXTby71krG5DWP6pej8oLJ0LGO6r8/r
            kK0I+2hyH1wLUeqhkND/Ol9EP2GAPeWsSG3rnk+9dszff/lwQwAm9m9NI4vEv253
            ujHzKL2SWs+J9cZoY3Lb4V2IezE2FIu/r5PlsMa87FI0vdUDxMDrBtwQ66+rKFy1
            wctjFyxd3Rqc28ysMg9mJIrLoOOZvi1pRO9sIAtccp/a2BlCa61eZuzvZ4Riy6KL
            42yOH7RItWyTFuOm42xw4jjsH8rho6EToJZBabHpq33HeduF8xDF/41LUbbVSDd4
            HfHH6jIjwjHkZ5y902H6lZ2baNBs9RICJ1if3otam7b1JRsmgL3SaHFcWii5Ve0v
            syMqK5/G6yJOGUP20rOkm8J9/D1lWyB3jbYajAEshXvCKz60n4sq50j14TtlzfCQ
            IdJQQd2p5vwQwuSq0Lu5fivx8h7I1IX/aKJdAc813mciZ2DSvjbAPgwYiiC/dFGf
            vxgg1vC5BX2fxvMGA6I0R6kRQfsYQGBVfyp9tyxbcKSQacwaj6D/UigZ20URaTTS
            XgGFj3ZR0ysQH4mvcM9dFYmDW/TbCdCHi89dSvpW63jzg0K2L+h5/A8GTd/HFRSL
            B8VqjM2rfhvz1cQHpttnSRfxjMLgE8zuOxZSVSlqLKUmXvzJ71841CA0Be/gyas=
            =QrFv
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: postgres-keycloak-superuser
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:gPXY6qOsuJ8=,iv:B42gGUbYDVJVVNkUA1z2OW5nTJpFORaQ/n1nuMlrKYc=,tag:tOosx/osvrxj6yN79cc3tA==,type:str]
    password: ENC[AES256_GCM,data:GDk9CFBSvUq9Lnrn03c9/wkGujnhhXX2,iv:s/Ai9aw9kaBJMeqpC3N2usqnlymeDt9na+iLO2YJsTM=,tag:IMVOdoBeWFVI71NWm6FZnA==,type:str]
sops:
    lastmodified: "2025-07-14T19:27:55Z"
    mac: ENC[AES256_GCM,data:5zKl9M0dXki+N8b+ALzI2dRt7FZKxR/kZo0O71C3J2nEmGf1DGWZeTSPS1n4s0MHM+HIuv6gCi2lQ9tBtbU8mXfPqOeuy0a8Qq9+D5y06SKENbGOd6auOPyeF0QeTJk+gyRsDfTblVO5fCjrhQ6MdmOV+urAj5CVBAo/5uRxRLA=,iv:r9aByqVLpnkpCifRNu7M8Sh9D98XD+PTA8gNuNChCRw=,tag:uqIvIYJo2DD3XM3OL62GgQ==,type:str]
    pgp:
        - created_at: "2025-07-14T19:27:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA06fffInlMOLAQ/6Au0JZMbpB6BYDBlLoRlgBOImfbuDiVUhmYP7OQeZZDPg
            h3kRjtFwvVO8z6lxbpAhAMVkz2IHTFsypovE4dY2E7uL15qo59hhOehT6m9WKwG5
            rEVMNf8C59QwddZ7OhqbofwbswZCBNXodZXTby71krG5DWP6pej8oLJ0LGO6r8/r
            kK0I+2hyH1wLUeqhkND/Ol9EP2GAPeWsSG3rnk+9dszff/lwQwAm9m9NI4vEv253
            ujHzKL2SWs+J9cZoY3Lb4V2IezE2FIu/r5PlsMa87FI0vdUDxMDrBtwQ66+rKFy1
            wctjFyxd3Rqc28ysMg9mJIrLoOOZvi1pRO9sIAtccp/a2BlCa61eZuzvZ4Riy6KL
            42yOH7RItWyTFuOm42xw4jjsH8rho6EToJZBabHpq33HeduF8xDF/41LUbbVSDd4
            HfHH6jIjwjHkZ5y902H6lZ2baNBs9RICJ1if3otam7b1JRsmgL3SaHFcWii5Ve0v
            syMqK5/G6yJOGUP20rOkm8J9/D1lWyB3jbYajAEshXvCKz60n4sq50j14TtlzfCQ
            IdJQQd2p5vwQwuSq0Lu5fivx8h7I1IX/aKJdAc813mciZ2DSvjbAPgwYiiC/dFGf
            vxgg1vC5BX2fxvMGA6I0R6kRQfsYQGBVfyp9tyxbcKSQacwaj6D/UigZ20URaTTS
            XgGFj3ZR0ysQH4mvcM9dFYmDW/TbCdCHi89dSvpW63jzg0K2L+h5/A8GTd/HFRSL
            B8VqjM2rfhvz1cQHpttnSRfxjMLgE8zuOxZSVSlqLKUmXvzJ71841CA0Be/gyas=
            =QrFv
            -----END PGP MESSAGE-----
          fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
