apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-gluetun-secret
stringData:
  SERVER_CITIES: ENC[AES256_GCM,data:53rMJGTrlj7g,iv:gXaplcowdLo9GABCegWJRT4fq0evp7R6l4bG/dS6fjE=,tag:MNj15yHLafwWPjYT95+42w==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:GluOkPi9o4Gl74k=,iv:jVhjtSS/bszNoy37Nm1mIcPxVYfNBUs6Nxxv0U4y6Ts=,tag:jSW+krkigZLuvQS1zc6/wg==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:Jzmd8jMZdQ==,iv:wsGPObcuCTVZOGlOwHtlgWop3/TvghSOuPE+fX+YvJE=,tag:uirzyIH2ofd7J/2yDkFAmg==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:kKeQ028jmTNE,iv:SasbFvO8/35vunwdsxY0CYDzh+ofp1KVn2OPp8THlw4=,tag:X7PJUIutMoPjXkJpnCDLkA==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:zZ9zxCA5Yltz42BwOWcVvMUrPcySgPIrcZgBOjfk363LP8/FrJ4F4gKhj8P/5lm9,iv:EuY1DDBbvbv35LANBgV9vivYiikfWRTLY7kxDUBVZWM=,tag:QVPe5iObJvPYUGTVq4iyIQ==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:GXN61VuTagKaiYnt+5Anzfy/MCesWyT8ywW2KfxcXG4RuuC9/Y0pYOgwHAc=,iv:f/66+fc/AHVJWVYXT8naPKdJ+YFLY4mekSRVwxEGJ+g=,tag:teuzRy8nk0Lt5NDdhHwUGA==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T11:12:55Z"
  mac: ENC[AES256_GCM,data:RfxA3yWCPlgwZhHT1naf4m4dCPazNQVx4Z/9xAgSKQ6secNLh8gEhyJSLudX4gfnkxp53CB8Y5p/XhaylkiUfCP0c3PBxap2hzfzqdWFdP1BU6g05gPXLYjuWxpzQJ2VOvnd93JX2ukFnFSRrruo6M4EJBhHVQ7V1EP3PUVEgA8=,iv:j0o/DdEBnNBgfpuiw5bMs60EIbiTcnbBJQSOcHNzsQE=,tag:1nW5mTMkTzfnjepnKjsr2w==,type:str]
  pgp:
    - created_at: "2026-09-19T11:12:55Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/5AW5QDsH9BKD6QED3btPwKFbWbNquBR45ZkH82Q9Ybjfq
        dDK2nZhC6UPRv1cjUeIFgO/Tjg3/2xWFaUQFODD2/MZigNq1oOvj2rGxip6u/6mE
        Hvp7a//44c0sFA/8wRHdVb9/WTTX7ltYu4QuTkDpOC3N6sA1JesH+UThgoxtrfLN
        Sox1phZ2BvsmQ+LrPIFhnDHkJnIgXtcsIxz1YIpLj3A7n3CODHRtceYkeTdy1zYl
        TJPzyQ1ly2zVNK7KFeiTLWs3cn9rKlgTFVG0Q5ioOg96Ocb4I6xOTSVTOOwi7a5m
        ADNY3OMGsOsyWwgRrmYMM+9mzfy/dNfyzQF1x4jgw/q0f4zqdivHyRUQjCCVREha
        TO+VDl+wUHcnfGPlNXADk/y8449UF0Md9umfMCdG2vNfo9ktS3/31UEmAruH7/NG
        bViM1v+FAY4y9sllGRkf5gN6NhBYN7Pz+KSAKespJf0yMDruDXZptGF7JyVpQZLQ
        YzhBLQhy+upOulxIOEdC8WhWSCOIZ9vm7Dc/sjvrrdIwKwFM5GbwUjMkkLUk1Aok
        iNsscRIOvdyWbjUm6EnQN0KlmsU00yr8zSVwbTkvMSHWVNJtV+BIP4SnlVYEer7B
        yhk55W819UAsZKbIYhiYzi6VCPEc/mV2PRLhSoRv7VV1AAB9p5vIgQVJqsRcOIrS
        XgH+Y7vN7LQVfOyAiiDTh3Nqa+Hdp06wMzg3IWsLN72T3Cv3KM0ujPOmtvKea96j
        yqz/o4bFAJ42UXb68UT1RDPvtdfXx5ZDT+LdZY04R/z1e/6MDUoKyoz7xRYFWnE=
        =OFVR
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:RAu1I35xcGAoEFIS6WRegI1L5/7sNp3K2kcjZ5hdsMA=,iv:R3XfiCctcglZ3YnZqFdf4o1fK7C2hgsjEcHoh+R448o=,tag:Pp2GWstZ/tdHvh+QQ8A+5Q==,type:str]
  NZB_KEY: ENC[AES256_GCM,data:ex4wBemD/6G1OVBQ58N/fX1YeVXRE7bBYuOVK53RRvU=,iv:i3hy9nxaGIjIEXlU3TSZ39cgZaLLzIh0RIlRl5SCOtE=,tag:I9kUnbA1ImmvSUo72j8bNw==,type:str]
  ABS_BEARER: ENC[AES256_GCM,data:w9qtwHeMFW532yM4qLq+CUtymrC9tqzfJbfiY7mNbKwVo3czeY1sLK5Bc5hgwoMVEydrJRRMoGSIiRNn9txMVNgdmaBCpJCZFff1WTQOrQ5d5Oo8TixnDXWSaryvQXAsI62zun7YiqT0x3fuwkwsZtD+00s/M23S68W/r+xi1ZKTPq07BauH5NS/qrE+nCJrpPRfUZmvIvGhPSX6FmPgpudzWQUokR5xtRg6xJ6rzYU0Vk5zzhb+pDJLJOmQkf2e4A6zRxyZRz2Xs3KSCh6F8A==,iv:k6qrKHG2nnqLJWJ0iDjbGOVEBgkuqTdKmYog+TzF8zg=,tag:BPWVmTaxWrDGJ+2scTVPPA==,type:str]
sops:
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T11:12:55Z"
  mac: ENC[AES256_GCM,data:RfxA3yWCPlgwZhHT1naf4m4dCPazNQVx4Z/9xAgSKQ6secNLh8gEhyJSLudX4gfnkxp53CB8Y5p/XhaylkiUfCP0c3PBxap2hzfzqdWFdP1BU6g05gPXLYjuWxpzQJ2VOvnd93JX2ukFnFSRrruo6M4EJBhHVQ7V1EP3PUVEgA8=,iv:j0o/DdEBnNBgfpuiw5bMs60EIbiTcnbBJQSOcHNzsQE=,tag:1nW5mTMkTzfnjepnKjsr2w==,type:str]
  pgp:
    - created_at: "2026-09-19T11:12:55Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/5AW5QDsH9BKD6QED3btPwKFbWbNquBR45ZkH82Q9Ybjfq
        dDK2nZhC6UPRv1cjUeIFgO/Tjg3/2xWFaUQFODD2/MZigNq1oOvj2rGxip6u/6mE
        Hvp7a//44c0sFA/8wRHdVb9/WTTX7ltYu4QuTkDpOC3N6sA1JesH+UThgoxtrfLN
        Sox1phZ2BvsmQ+LrPIFhnDHkJnIgXtcsIxz1YIpLj3A7n3CODHRtceYkeTdy1zYl
        TJPzyQ1ly2zVNK7KFeiTLWs3cn9rKlgTFVG0Q5ioOg96Ocb4I6xOTSVTOOwi7a5m
        ADNY3OMGsOsyWwgRrmYMM+9mzfy/dNfyzQF1x4jgw/q0f4zqdivHyRUQjCCVREha
        TO+VDl+wUHcnfGPlNXADk/y8449UF0Md9umfMCdG2vNfo9ktS3/31UEmAruH7/NG
        bViM1v+FAY4y9sllGRkf5gN6NhBYN7Pz+KSAKespJf0yMDruDXZptGF7JyVpQZLQ
        YzhBLQhy+upOulxIOEdC8WhWSCOIZ9vm7Dc/sjvrrdIwKwFM5GbwUjMkkLUk1Aok
        iNsscRIOvdyWbjUm6EnQN0KlmsU00yr8zSVwbTkvMSHWVNJtV+BIP4SnlVYEer7B
        yhk55W819UAsZKbIYhiYzi6VCPEc/mV2PRLhSoRv7VV1AAB9p5vIgQVJqsRcOIrS
        XgH+Y7vN7LQVfOyAiiDTh3Nqa+Hdp06wMzg3IWsLN72T3Cv3KM0ujPOmtvKea96j
        yqz/o4bFAJ42UXb68UT1RDPvtdfXx5ZDT+LdZY04R/z1e/6MDUoKyoz7xRYFWnE=
        =OFVR
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  version: 3.13.3
