apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-gluetun-secret
stringData:
  SERVER_CITIES: ENC[AES256_GCM,data:X8H34fhj+oKv,iv:5ftxxme/U+9FiKv+yIFgNEz221IRid+EAKOptLYzG2w=,tag:Pmwpu3Nnq7GJbnc8JEiSFQ==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:LG/xULgTSzydapU=,iv:dT6JQWLbzuvWMTyyTKG6YXSJ5Yl7vC4Z0FIHlGz898c=,tag:H/Pn/qhlItisvxbVhYcH9A==,type:str]
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:OPgBw4OVtw==,iv:BT+tcFGa3srTgPiO6VIp+J3apOAseWYXH2IsXiJZVn8=,tag:lMVsVUTpk1sbCaW8/jW+2Q==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:yM2nTYy9Tpja,iv:sIDapTvryx/4xcikNjXTne1D7cQcEGKlQKD2wGCZFnA=,tag:oqfXqsvF0BdWobzEsmYsNQ==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Yc7iisYT/SjG7ePaNECv3AH2fSjhHBcIBHSNMtrLRzmBQ9qhqj8zgd4Vgt57+6dE,iv:MuuXOO6/jSnspX2EagM8m5nJWwo9gXVWsbAa2ZrU02A=,tag:ft3T5MnLLCuY7tTPhcGmlg==,type:str]
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:gwvWeZtvHV2sH22ztX3S3asFqCDMczm6ztfZ25uOA5d0NNqNpdM+GcFuq34=,iv:dWaYNwdNKKiTUpiQdSTEkKCz3nFqOiij/Uy+HtBJzaQ=,tag:mpqbT2jMfVGvmYQaUv6Gyw==,type:str]
sops:
  lastmodified: "2026-02-25T14:46:49Z"
  mac: ENC[AES256_GCM,data:UVHMo5+N6f25dB1hQXDBKvTutd2lW0c+7wAF54eG//jFJy+Yu32alb0ER0tCxbNQyRGkgfxLSvXxZ3JRyl87KIsGElQT1qTdpR/oa2YEWl6Xasokh1W36Vg3mFVsEcwIx/xszK3QOGDU4YToD3vMwdogYNkE6OA3J6uIUC6sa50=,iv:lVurzFOqjwV3tGTidC9yisbcxNmR5nqK7Sq5ZRVXdGo=,tag:LlS1neRH1Nc0xjOX3ttsEQ==,type:str]
  pgp:
    - created_at: "2026-02-25T14:46:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//UGVVeKJ566YG/Uceg/im4eUuZ3UCV/bnXN1fIjBCTvP6
        JGiiOuxdkkhq6ua15qxg3nAJc5CAx3xlTJB2D6A0vQEoS6KR8TQhdKIyw4hcKJPt
        EfTKieXspRNaylK2/RzMKmh0GN7slbIJI1pipaTz50Ll/nco7AQroX6gL9L6Fwji
        SEDi0QnLtRRgC8XieP2y6QkQCEFRTX8jq04FP7rStIZWvT3znJEhVXxIEbx76/sL
        UFhuOHyvCXbhId6ngBkM6nP+Z7bEDrOlvbHJVZC2Q9//TsfescLKSOhgzIfPUU/c
        BxPlOicDRO1OScMCgGDEM5dGBHf7QIM7ynm92HePG3gKxeKmvIC2d4LzKQv6W5yN
        Tec8TL7gciV29GrRm4J/QihmkzwDpbZABZJyxcpiDIPHyC8R0YrEc9dknKP/YTyp
        2D7VNc0obEgUJC8KG3uaO9RIq9AcMTuvbdi1p3MjtrY2/EM19mS+tEpc4CiWaEuO
        DugpJ0uVNKEVuRQ8+ucdl+3fK3MFhtJLmO/ST8MVyvMNhdT1PxCdj2qKlR9xt6jT
        HoQiTjxGTnR7ObGRp7CYot/+zu5BpzpnEluUhr4B33s+mChiNViAdjZc3BlLkhuv
        lHgTU2TkTGEYLjYxeIltsuKoTQiHVNzurN8fjzTsI3ul71L+HvHZ6NasSU0NVdzS
        XgEEnd/C5ulhSZv6IAxPATMxDBwdFUopbtxUbqYqtVjMK/wjc2LreuoZqDMybRzZ
        1I8R4EWbgXWZS2iN+ushAg/fV3qx/YdcYdwDv2mNxKau7rhDhukU+WKd/5qvLY0=
        =P9UT
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  API_KEY: ENC[AES256_GCM,data:cSpKCHP8vkKx0O0eUFhykIlOJE7pO9gTUu9vy5ex7vg=,iv:hP5QBW6f8PfQWseXmEULn4SAa2hb7EdVSSxUAmTm/u4=,tag:gHQDy0y+wFaGZI/kaKt7Vw==,type:str]
  NZB_KEY: ENC[AES256_GCM,data:rs8MRjKIsnPbpTzp+bapasXYbP/5ep5xurLjxDFcwtE=,iv:kdPg9OdPRxsTIVPfQw/2KHm7zFBiYEqlr5pD52rTMog=,tag:q53c+MshTWBcwXbApzhIqA==,type:str]
sops:
  lastmodified: "2026-02-25T14:46:49Z"
  mac: ENC[AES256_GCM,data:UVHMo5+N6f25dB1hQXDBKvTutd2lW0c+7wAF54eG//jFJy+Yu32alb0ER0tCxbNQyRGkgfxLSvXxZ3JRyl87KIsGElQT1qTdpR/oa2YEWl6Xasokh1W36Vg3mFVsEcwIx/xszK3QOGDU4YToD3vMwdogYNkE6OA3J6uIUC6sa50=,iv:lVurzFOqjwV3tGTidC9yisbcxNmR5nqK7Sq5ZRVXdGo=,tag:LlS1neRH1Nc0xjOX3ttsEQ==,type:str]
  pgp:
    - created_at: "2026-02-25T14:46:49Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ//UGVVeKJ566YG/Uceg/im4eUuZ3UCV/bnXN1fIjBCTvP6
        JGiiOuxdkkhq6ua15qxg3nAJc5CAx3xlTJB2D6A0vQEoS6KR8TQhdKIyw4hcKJPt
        EfTKieXspRNaylK2/RzMKmh0GN7slbIJI1pipaTz50Ll/nco7AQroX6gL9L6Fwji
        SEDi0QnLtRRgC8XieP2y6QkQCEFRTX8jq04FP7rStIZWvT3znJEhVXxIEbx76/sL
        UFhuOHyvCXbhId6ngBkM6nP+Z7bEDrOlvbHJVZC2Q9//TsfescLKSOhgzIfPUU/c
        BxPlOicDRO1OScMCgGDEM5dGBHf7QIM7ynm92HePG3gKxeKmvIC2d4LzKQv6W5yN
        Tec8TL7gciV29GrRm4J/QihmkzwDpbZABZJyxcpiDIPHyC8R0YrEc9dknKP/YTyp
        2D7VNc0obEgUJC8KG3uaO9RIq9AcMTuvbdi1p3MjtrY2/EM19mS+tEpc4CiWaEuO
        DugpJ0uVNKEVuRQ8+ucdl+3fK3MFhtJLmO/ST8MVyvMNhdT1PxCdj2qKlR9xt6jT
        HoQiTjxGTnR7ObGRp7CYot/+zu5BpzpnEluUhr4B33s+mChiNViAdjZc3BlLkhuv
        lHgTU2TkTGEYLjYxeIltsuKoTQiHVNzurN8fjzTsI3ul71L+HvHZ6NasSU0NVdzS
        XgEEnd/C5ulhSZv6IAxPATMxDBwdFUopbtxUbqYqtVjMK/wjc2LreuoZqDMybRzZ
        1I8R4EWbgXWZS2iN+ushAg/fV3qx/YdcYdwDv2mNxKau7rhDhukU+WKd/5qvLY0=
        =P9UT
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
