---
- name: Add key
  ansible.builtin.apt_key:
    url: "{{ nvidia_docker_repo_gpg_url }}"
    state: present
  when: nvidia_docker_add_repo
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  become: true

- name: Add repo
  ansible.builtin.get_url:
    url: "{{ nvidia_docker_repo_base_url }}/stable/deb/{{ _ubuntu_repo_file_name }}"
    dest: "{{ _ubuntu_repo_file_path }}"
    mode: "0644"
    owner: root
    group: root
  when: nvidia_docker_add_repo
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: nvidia-container-runtime
    state: present
    update_cache: true
  notify: Restart docker
  environment: "{{ proxy_env if proxy_env is defined else {} }}"
  become: true
