apiVersion: v1
kind: Secret
metadata:
  name: navidrome-secret
stringData:
  ND_LASTFM_APIKEY: ENC[AES256_GCM,data:cMRVWObo8nPuagJpLZZKtayBAdI64X2ET7e/ucD0eDk=,iv:o7AFgz8sCT3N/DfPv96U0+MbUUInMxvoYVR6+YeLA3M=,tag:QisVQFq0NbEOp7ZSeEzN1A==,type:str]
  ND_LASTFM_SECRET: ENC[AES256_GCM,data:FLd4zbWnWnGsDiJt/FvTJZcH0faLrSdH5qdx/ifdJj8=,iv:/tHyHT5mjqoJiz5DV2G2TPz+gBEl3bU7b+0fc41wBwo=,tag:IdIYXXvTjNBgQA066gH7uA==,type:str]
sops:
  lastmodified: "2026-03-04T12:39:31Z"
  mac: ENC[AES256_GCM,data:W2TyZd9Q28mOSiQ83rNLC7iRaNb655grdJtGXW5QhmVFVgvtlEsZDNzB5RifOnpAVxQ/S6DhdA00NGFm+RiFLx5vsQlRtnHM/s3B1jaFQ7VnxWgN7GxLnMz5bBuioffBkpD8SH4LlARnx6+Ss4ftk+uJletNCdqAP9v9fmGyJuE=,iv:IG+QzlF8WsDY6zAStB7CAKzwJ3eGk7B/Z29VhUuIzyM=,tag:f38QdSYh7FT0PyqZuuzR5w==,type:str]
  pgp:
    - created_at: "2026-03-04T12:39:31Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA06fffInlMOLAQ/9FOJghP+RIIKW7C51eZnr0SEf1jl+SxmDgIiJFb4/SP96
        0mDAGLEjGJvzCkXDFdcX8owY/Mt27CEN5L85dCo4vKK1oePJKMS0NDBEtOOheYwM
        WMYLkyL2ei3MvR8acl480meEqE++o/NzQNZdp5MXwuWYVf2rcefp/apAmzOBGFmo
        WG0VDU1DIhnIVrQrAH4RVDhdMNgRzvHBRNByaBo7mb22/ysqZNYS+OE+LfnzDa1Y
        DHL+7/vWWeQYfMBb+n2kCXchSLyJ4ZkITT2lGuWiuleThrOCv5bkVgubbX3Dxz4c
        A7PnXD4pv7RQQPSQzDl6C0fAPBwAVV1nFJHFLhQkCs8TOKu3kMzFWyptw249Pa2R
        8HLictNvEC+GH/XAAUL6RfE2ylTS/otCrTgUdnMNhzRRE8zOY+QbBAUQEe9ZhAUv
        qhMtd0pzhaUvnmU99cxdsouyxaJ47XcK9/EjwN0CjVShpX1SRPVlujp8PpXLKPQ8
        80egmQs4n5ZzBZZhS93i7g9SfqKeKAQG0Bqc3OZO4UMlAqgf5mpDE+RQPMoj6eWw
        lGNImkdzz/lO2KI1KQQhWIVT5DZ4xfNbxGjMoL6enjGIUPppsazWL/1ZnzI5YIcK
        a+l5fNB0fZWm4dWjb7Ohxw3Z48fPlK/lm5xGOUk+Q+nrqv6f2sh3Ld4gMU6aHpbS
        XAG6hR4xGguO6AhI9OUKQJxo/9SeI7BL0V04UYxcDjR9tTCh1CYXFBPMrPg6sK38
        /v2HLHZs80OMkgqg20YL+i87YpuJJME77uQZAnN2Mvnc3MREU69gZoZ2zIbg
        =4xX0
        -----END PGP MESSAGE-----
      fp: E9F6BEBC269B2E8B8AE07E3784A740B5B323BDD3
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
