---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obsidian
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      obsidian:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/obsidian
              tag: 1.9.12
            env:
              TZ: ${TIMEZONE}
              PUID: 1000
              PGID: 1000
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 1Gi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000

    ingress:
      app:
        className: internal
        hosts:
          - host: &host "obsidian.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /config
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Gi
        globalMounts:
          - path: /dev/shm
