---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homarr-backup-job
data:
  backup.sh: |
    #!/bin/sh

    TIMESTAMP=$(TZ="${TIMEZONE}" date +"%Y-%m-%d_%H-%M-%S")
    FILENAME="export-$${TIMESTAMP}"
    TARGET_DB_FILENAME="$${TIMESTAMP}.sqlite"
    FILENAME_TAR="$${FILENAME}.tar.gz"

    echo "starting homarr backup $${FILENAME}"
    sqlite3 /mnt/homarr-database/db.sqlite ".backup '/mnt/backup/$${TARGET_DB_FILENAME}'"
    tar czf /mnt/backup/$${FILENAME_TAR} -C /mnt/backup $${TARGET_DB_FILENAME}
    rm /mnt/backup/$${TARGET_DB_FILENAME}
    echo "finished homarr backup"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: homarr-backup
spec:
  schedule: "30 3 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 60
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: homarr
                  topologyKey: kubernetes.io/hostname
          containers:
            - name: backup
              image: alpine/sqlite:3.51.2
              command: ["sh", "/scripts/backup.sh"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsNonRoot: false
              volumeMounts:
                - name: homarr-database
                  mountPath: /mnt/homarr-database
                - name: backup-nfs
                  mountPath: /mnt/backup
                - name: script-volume
                  mountPath: /scripts/backup.sh
                  subPath: backup.sh
          restartPolicy: OnFailure
          volumes:
            - name: homarr-database
              persistentVolumeClaim:
                claimName: homarr-database
                readOnly: true
            - name: backup-nfs
              persistentVolumeClaim:
                claimName: backup-nfs-${APP}
            - name: script-volume
              configMap:
                name: homarr-backup-job
                items:
                  - key: backup.sh
                    path: backup.sh
                defaultMode: 0555 # read and execute
