apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret.sops.yaml
  - ../../base/homarr
patches:
  - path: values.yaml
    target:
      kind: HelmRelease
      name: homarr