apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: default
spec:
  values:

    ingress:
      enabled: true
      className: nginx
      hosts:
        - host: dash.fdk.codes
          paths:
            - path: /
